containernetworking/plugins

Godeps/Godeps.json, README.md, plugins/meta/portmap/README.md, plugins/meta/portmap/chain.go, plugins/meta/portmap/chain_test.go, plugins/meta/portmap/main.go, plugins/meta/portmap/portmap.go, plugins/meta/portmap/portmap_integ_test.go, plugins/meta/portmap/portmap_suite_test.go, plugins/meta/portmap/portmap_test.go, plugins/meta/portmap/utils.go, test.sh, vendor/github.com/containernetworking/cni/libcni/api.go, vendor/github.com/containernetworking/cni/libcni/conf.go, vendor/github.com/coreos/go-iptables/LICENSE, vendor/github.com/coreos/go-iptables/iptables/iptables.go, vendor/github.com/mattn/go-shellwords/.travis.yml, vendor/github.com/mattn/go-shellwords/LICENSE, vendor/github.com/mattn/go-shellwords/README.md, vendor/github.com/mattn/go-shellwords/shellwords.go, vendor/github.com/mattn/go-shellwords/util_posix.go, vendor/github.com/mattn/go-shellwords/util_windows.go
This is a fairly standard iptables-based portmapping plugin. It supports ipv4 and ipv6.
This replaces the proposed plugin in the [cni repository](https://github.com/containernetworking/cni/pull/378).
=> iptables-based portmapping plugin

pkg/ns/ns_linux.go
Use unix.Setns() instead of manually re-implementing it using
unix.Syscall().
=> pkg/ns: use unix.Setns() instead of open coding it

pkg/ns/README.md
moved over https://github.com/containernetworking/cni/pull/331 since the plugin/lib split
added link to blog post from Weave folks 
cc: @bboreham @dcbw
=> pkg/ns readme: expand on danger of ns switching in long-lived programs

pkg/ip/cidr.go, plugins/ipam/host-local/README.md, plugins/ipam/host-local/backend/allocator/allocator.go, plugins/ipam/host-local/backend/allocator/allocator_test.go, plugins/ipam/host-local/backend/allocator/config.go, plugins/ipam/host-local/backend/allocator/config_test.go, plugins/ipam/host-local/backend/allocator/range.go, plugins/ipam/host-local/backend/allocator/range_test.go, plugins/ipam/host-local/backend/disk/backend.go, plugins/ipam/host-local/backend/store.go, plugins/ipam/host-local/backend/testing/fake_store.go, plugins/ipam/host-local/host_local_test.go, plugins/ipam/host-local/main.go
This change allows the host-local allocator to allocate multiple IPs. This is intended to enable dual-stack, but is not limited to only two subnets or separate address families.
Migrated from containernetworking/cni#451.
=> ipam/host-local: support multiple IP ranges

plugins/meta/portmap/main.go, plugins/meta/portmap/portmap_integ_test.go, plugins/meta/portmap/portmap_test.go
This also adds more testing around configuration parsing.
This was inspired by k8s bug that passed a port number of 0, but I realized that there was some logic not under test that really should be.
=> portmap: Don't accept a port number of 0

plugins/main/bridge/bridge.go, plugins/main/bridge/bridge_test.go
This change adds support for IPv6 container/pod addresses to the CNI
bridge plugin, both for dual-stack (IPv4 + IPv6) and for IPv6-only
network configurations.
The proposed changes support multiple IPv6 addresses on a container
interface. If isGW is configured, the bridge will also be configured with
gateway addresses for each IPv6 subnet.
Please note that both the dual-stack functionality and support for multiple
IPv6 container/gateway addresses depends upon containernetworking/cni
[PR #451](https://github.com/containernetworking/cni/pull/451) "ipam/host-local: support multiple IP ranges".
The bridge plugin changes being proposed here could potentially be committed
independently from this host-local plugin change; however the dual-stack and
multiple IPv6 address functionality that is …
=> bridge: Add support for IPv6 to bridge plugin

plugins/meta/flannel/flannel.go, plugins/meta/flannel/flannel_test.go
This prevented flannel from returning any useful information about created interfaces. This broke plugin chaining.
Fixes: #23
=> flannel: set the cniVersion on the delegated config

pkg/ip/addr.go, pkg/ip/ipforward.go, pkg/ip/ipmasq.go, pkg/ipam/ipam.go, pkg/testutils/ping.go, plugins/main/ptp/ptp.go, plugins/main/ptp/ptp_test.go
* Wait for addresses to leave tentative state before setting routes
* Enable forwarding correctly
* Set up masquerading according to the active protocol
=> ptp: add ipv6 support

plugins/meta/portmap/portmap_integ_test.go, plugins/meta/portmap/portmap_suite_test.go
The source address selection was random, and sometimes we picked a
source address that the container didn't have a route to. Adding a
default route fixes that!
=> plugins/portmap: fix test flake

plugins/main/bridge/README.md, plugins/main/bridge/bridge.go, plugins/main/bridge/bridge_test.go
This PR is identical to https://github.com/containernetworking/cni/pull/441  which was closed since the repo was moved.
=> bridge: add support for promiscuous mode

plugins/meta/tuning/tuning.go, plugins/meta/tuning/tuning_suite_test.go, plugins/meta/tuning/tuning_test.go
=> tuning: pass prevResult through

plugins/ipam/host-local/README.md, plugins/ipam/host-local/backend/allocator/allocator.go, plugins/ipam/host-local/backend/allocator/allocator_test.go, plugins/ipam/host-local/backend/allocator/config.go, plugins/ipam/host-local/backend/allocator/config_test.go, plugins/ipam/host-local/backend/allocator/range.go, plugins/ipam/host-local/backend/allocator/range_set.go, plugins/ipam/host-local/backend/allocator/range_set_test.go, plugins/ipam/host-local/backend/allocator/range_test.go, plugins/ipam/host-local/host_local_test.go, plugins/ipam/host-local/main.go, plugins/main/bridge/bridge_test.go, plugins/main/ptp/ptp_test.go
In real-world address allocations, disjoint address ranges are common. Therefore, the host-local allocator should support them.
This change still allows for multiple IPs in a single configuration, but also allows for a "set of subnets."
I'm not entirely happy with the configuration format - currently an array of arrays. I could be convinced to write a custom JSON deserializer that accepts either an array or a single object.
Fixes: #45
=> ipam/host-local: support sets of disjoint ranges

plugins/main/bridge/bridge.go, plugins/main/bridge/bridge_test.go
* Don't set the MAC, send gratuitous arp instead
* Set the bridge's MAC to itself
* Only disable DAD when necessary
Fixes: #60 #59 #52
=> bridge: various fixes

plugins/ipam/host-local/backend/disk/backend.go, test.sh
Without this change
```
go vet ./plugins/ipam/host-local/backend/disk
```
returns
```
plugins/ipam/host-local/backend/disk/backend.go:54: literal copies lock value from *lk: disk.FileLock
exit status 1
```
see the [go vet heuristic here](https://github.com/golang/go/blob/d77d4f509c61a8e1eaadeabca86ee48710bd8030/src/cmd/vet/copylock.go#L230-L232).
=> host-local FileLock is used by value instead of by reference

test.sh
~~Don't merge yet, this depends on:~~
~~- #65: Upgrade to Go 1.9 so that we get the benefits of [ignoring `vendor` by default](https://golang.org/doc/go1.9#vendor-dotdotdot)~~ 
*Removed this requirement*
~~- #66: fix up lingering `go vet` warnings~~
*DONE*
**UPDATE**: no longer depends on Go 1.9, this is good-to-go as is.
=> Test all packages

.travis.yml, test.sh
may help reduce test-pollution due to namespace-affinity
see http://onsi.github.io/ginkgo/#parallel-specs
ref: https://github.com/containernetworking/plugins/pull/56#issuecomment-325675507
cc: @squeed
=> travis: run with ginkgo -p instead of go test

plugins/meta/portmap/echosvr/echosvr_test.go, plugins/meta/portmap/echosvr/init_test.go, plugins/meta/portmap/echosvr/main.go, plugins/meta/portmap/portmap_integ_test.go, plugins/meta/portmap/portmap_suite_test.go
this way we're not mixing goroutines and namespaces
when running 
```
ginkgo -untilItFails -timeout 3s -p
```
with the single integration spec focused, it used to fail after about 5 runs.  with this change, i got 95 successes in a row.
however, this won't fix everything.   when I unfocus the integration spec, I still get failures due to namespace affinity, but now after about 10 runs.
~~UPDATE: travis says `"nsenter": executable file not found in $PATH` :-(~~
Update: it's green! 🍏 💚 🥗 !
=> portmap integration test: echo server runs in separate process

pkg/ip/ipmasq.go, pkg/ip/link.go, pkg/ip/link_test.go, plugins/main/bridge/bridge.go, plugins/main/ipvlan/ipvlan.go, plugins/main/macvlan/macvlan.go, plugins/main/ptp/ptp.go, plugins/main/vlan/vlan.go
V6-only interfaces were throwing an error on teardown.
=> Fix ipmasq teardown on v6-only interfaces

plugins/host-device/host-device.go, plugins/host-device/host-device_suite_test.go, plugins/host-device/host-device_test.go
Here is a plugin for moving host devices into container network-namespace.
The only parameter is "device".
Please review and tell me how to test this plugin, because I wasn't able to run the tests (or found documentation about how to do so...).
=> added host-device plugin which adds a specified link to container

plugins/host-device/host-device.go, plugins/host-device/host-device_test.go
Fixes errors in the `host-device` plugin, and its test, which were introduced in #3.
Includes change from #73.
@containernetworking/cni-maintainers a couple other issues that I encountered while fixing this:
- should this plugin, and loopback, go to the trouble of returning a `cniVersion` that matches the config version?  Since neither one returns any kind of interesting result, I say no.  But its technically a spec violation...
- what should be the meaning of the `CNI_IFNAME` environment variable in this plugin?    The plugin ignores it today... but it could potentially substitute for the `device` config field.
Anyhow, this should at least get CI green again.
=> Host-device fixes

plugins/host-device/host-device.go, plugins/host-device/host-device_test.go
`host-device` is using non-exist packages.
Signed-off-by: Lantao Liu <lantaol@google.com>
=> Newly added `host-device` doesn't compile.

plugins/ipam/dhcp/daemon.go
There are at least two reasons why a lease is not present:
* The dhcp ipam daemon was restarted
* ON add the IPAM plugin failed
Don't fail the IPAM invocation when the lease is not present, to allow
proper device cleanup on CNI delete invocations.
=> Don't let DHCP IPAM plugin fail on missing lease

.travis.yml, Vagrantfile
Go 1.9 is out, 1.7 is now no longer maintained.
Reference: https://golang.org/doc/devel/release.html#policy
See also: https://github.com/containernetworking/cni/pull/499
=> Golang versions: add 1.9, drop 1.7

pkg/ip/link.go
For some reason no addresses on the interface returned an error, despite
having a testcase that explicitly tested for success.
=> pkg/ip: don't return error from DelLinkByNameAddr() if no addresses exist

Godeps/Godeps.json, plugins/ipam/host-local/backend/disk/backend.go, plugins/ipam/host-local/backend/disk/disk_suite_test.go, plugins/ipam/host-local/backend/disk/lock.go, plugins/ipam/host-local/backend/disk/lock_test.go, plugins/ipam/host-local/host_local_test.go, plugins/linux_only.txt, vendor/github.com/alexflint/go-filemutex/LICENSE, vendor/github.com/alexflint/go-filemutex/README.md, vendor/github.com/alexflint/go-filemutex/filemutex_flock.go, vendor/github.com/alexflint/go-filemutex/filemutex_windows.go
Get host-local to work for Windows. This is required for Flannel VXLAN mode on Windows.
=> host-local: Update host-local IPAM to support Windows

plugins/meta/portmap/README.md, plugins/meta/portmap/chain.go, plugins/meta/portmap/chain_test.go, plugins/meta/portmap/main.go, plugins/meta/portmap/portmap.go, plugins/meta/portmap/portmap_integ_test.go, plugins/meta/portmap/portmap_test.go, plugins/meta/portmap/utils.go
This change improves the performance of the portmap plugin and fixes hairpin, when a container is mapped back to itself.
Performance is improved by using a multiport test to reduce rule traversal, and by using a masquerade mark.
Hairpin is fixed by enabling masquerading for hairpin traffic.
Fixes: #68
=> portmap: support hairpin, improve performance

pkg/ip/ipforward_linux.go, pkg/ip/ipforward_linux_test.go
This enables setup in a container env like systemd nspawn
where /proc/sys is mouted as read only.
Signed-off-by: Shengjing Zhu <i@zhsj.me>
=> pkg/ip: don't write to /proc/sys if ipforward enabled

pkg/ipam/ipam_linux.go
This change improves the performance of the ipam.ConfigureIface.
Some plugins are slow because of the ip.SettleAddress in ipam.ConfigureIface.
It seems to be only needed for IPv6, so should be skipped if only IPv4 is used.
=> pkg/ipam: Skip ip.SettleAddresses if only IPv4 is used

plugins/ipam/host-local/README.md, plugins/ipam/host-local/backend/allocator/config.go, plugins/ipam/host-local/backend/allocator/config_test.go
This allows for the runtime to dynamically request IP ranges.
Fixes: #95
=> ipam/host-local: Accept ip ranges as a runtime argument

plugins/ipam/dhcp/README.md, plugins/ipam/dhcp/daemon.go, plugins/ipam/dhcp/main.go
This diff adds -hostprefix option in dhcp daemon. This option could be used to run dhcp daemon as container because container cannot touch host's procfs directly. 
The diff changes dhcp daemon to touch procfs mounted to another path, like '/hostfs/proc'.
=> Add -hostprefix in DHCP daemon to run the daemon as container

plugins/ipam/dhcp/lease.go
Append a default route to the CNI reply if there's a gateway advertised.
Classless static routes (DHCP option 121) are now processed first.
If CSRs exist, static routes (DHCP option 33) and the gateway default
route are ignored as per RFC 3442.
Fixes: #51
=> Append default route and process route options in compliance with RFC 3442

pkg/ipam/ipam_linux.go
If CNI is about to configure an IPv6 address, make sure IPv6 is not disabled through the "disable_ipv6" sysctl setting.
This is a workaround for Docker 17.x which sets disable_ipv6=1 for all interfaces even if ipv6 is enabled in Docker.
Please see containernetworking/cni#531 for a more detail discussion of the issue.
=> Explicitly enable IPv6 sysctl

plugins/main/bridge/bridge_test.go
variable was unused.  Go 1.10 `go vet` complained.
=> bridge test: fix go vet error

.travis.yml, Vagrantfile
- test against Go 1.10
- stop testing against Go 1.8
since Go language maintainers no longer support 1.8
see: https://golang.org/doc/devel/release.html#policy
see also: https://github.com/containernetworking/cni/pull/538
=> travis: bump golang versions

plugins/ipam/dhcp/main.go
"error dialing DHCP daemon:" in cmdDel is duplicate with message in rpcCall
=> clean duplicated error message

build.sh
I need to build deb packages using golang-1.10 on Ubuntu Xenial which is
present in a non-default location while /usr/bin/go is at golang-1.6.
With this commit I can simply run:
`GO=/usr/lib/go-1.10/bin/go ./build.sh`
to use golang-1.10.
Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>
=> allow building with custom Go binary

pkg/ip/link_linux_test.go, pkg/ipam/ipam_linux_test.go, pkg/ns/README.md, pkg/ns/ns_linux.go, pkg/ns/ns_linux_test.go, pkg/testutils/netns_linux.go, plugins/ipam/dhcp/dhcp_test.go, plugins/main/bridge/bridge_test.go, plugins/main/host-device/host-device_test.go, plugins/main/ipvlan/ipvlan_test.go, plugins/main/loopback/loopback_test.go, plugins/main/macvlan/macvlan_test.go, plugins/main/ptp/ptp_test.go, plugins/main/vlan/vlan_test.go, plugins/meta/bandwidth/bandwidth_linux_test.go, plugins/meta/flannel/flannel_linux_test.go, plugins/meta/portmap/chain_test.go, plugins/meta/portmap/portmap_integ_test.go, plugins/meta/tuning/tuning_test.go, plugins/sample/sample_linux_test.go
Namespace creation had an unergonomic interface and isn't used, except for testing code. Remove it; downstream users should really be creating their own namespaces.
=> pkg/ns: remove namespace creation (and move to testutils)

plugins/ipam/static/README.md, plugins/ipam/static/main.go, plugins/ipam/static/static_suite_test.go, plugins/ipam/static/static_test.go
This changes to add 'static' CNI plugin, which provides to assign IPv4/v6 address statically from given config file. See README.md for the details.
=> Add static CNI plugin

integration/testdata/chained-bridge-bandwidth/network-chain-test.conflist, integration/testdata/chained-ptp-bandwidth.conflist, plugins/meta/bandwidth/bandwidth_linux_test.go, plugins/meta/bandwidth/main.go
To make it easier to supply bandwidth in a dynamic manner, the traffic shaping plugin should support a capability arg.
Fixes: #133
=> traffic shaping: take configuration via a runtimeConfig

.gitignore, build.sh, integration/integration_suite_test.go, pkg/ip/ip_suite_test.go, pkg/ipam/ipam_suite_test.go, pkg/ns/ns_suite_test.go, pkg/testutils/echosvr/init_test.go, pkg/utils/hwaddr/hwaddr_suite_test.go, pkg/utils/utils_suite_test.go, plugins/ipam/dhcp/dhcp_suite_test.go, plugins/ipam/host-local/backend/allocator/allocator_suite_test.go, plugins/ipam/host-local/backend/disk/disk_suite_test.go, plugins/ipam/host-local/host_local_suite_test.go, plugins/main/bridge/bridge_suite_test.go, plugins/main/host-device/host-device_suite_test.go, plugins/main/ipvlan/ipvlan_suite_test.go, plugins/main/loopback/loopback_suite_test.go, plugins/main/macvlan/macvlan_suite_test.go, plugins/main/ptp/ptp_suite_test.go, plugins/main/vlan/vlan_suite_test.go, plugins/meta/bandwidth/bandwidth_suite_test.go, plugins/meta/flannel/flannel_suite_test.go, plugins/meta/portmap/portmap_suite_test.go, plugins/meta/tuning/tuning_suite_test.go, plugins/sample/sample_suite_test.go, scripts/release.sh, test.sh
- bump to go 1.10
- Add a linker tag with the build version
- Remove fastbuild, go builds are cached now
- use better ginkgo suite names
=> build: some small improvements; bump to go1.10

pkg/testutils/cmd.go, plugins/ipam/dhcp/dhcp_test.go, plugins/ipam/host-local/host_local_test.go, plugins/ipam/static/static_test.go, plugins/main/bridge/bridge_test.go, plugins/main/host-device/host-device_test.go, plugins/main/ipvlan/ipvlan_test.go, plugins/main/loopback/loopback_test.go, plugins/main/macvlan/macvlan_test.go, plugins/main/ptp/ptp_test.go, plugins/main/vlan/vlan_test.go, plugins/meta/bandwidth/bandwidth_linux_test.go, plugins/meta/flannel/flannel_linux_test.go, plugins/meta/tuning/tuning_test.go, plugins/sample/sample_linux_test.go
Recent CNI specification changes require the container ID on ADD/DEL,
which the testcases were not providing.  Fix that up so things work
when this repo gets CNI revendored.
We switch over to CmdAddWithArgs()/CmdDelWithArgs() everywhere for simplicity, *except* the bandwidth plugin which has testcases that use a different interface name than is in its skel.CmdArgs.
@containernetworking/cni-maintainers @squeed @matthewdupre
=> plugins/testutils: pass CNI_CONTAINERID to plugins in testcases

plugins/main/host-device/host-device.go
If the device is in state up trying to set the name during `DEL` fails with "device or resource busy".
Steps to reproduce:
```
$> ip netns add demo
$> echo '{"cniVersion":"0.3.1", "device":"ens224"}' | CNI_COMMAND=ADD CNI_NETNS=/var/run/netns/demo CNI_IFNAME=eth0 CNI_PATH=/opt/cni/bin /opt/cni/bin/host-device
{
"cniVersion": "0.3.1",
"interfaces": [
{
"name": "eth0",
"mac": "fa:16:3e:ed:73:7b",
"sandbox": "/var/run/netns/demo"
}
],
"dns": {}
}
$> ip netns exec demo ifconfig eth0 up
$> echo '{"cniVersion":"0.3.1", "device":"ens224"}' | CNI_COMMAND=DEL CNI_NETNS=/var/run/netns/demo CNI_IFNAME=eth0 CNI_PATH=/opt/cni/bin /opt/cni/bin/host-device
{
"code": 100,
"msg": "failed to restore \"eth0\" to original name \"ens224\": device or resource busy"
}
```
=> host-device: Ensure device is down before rename

Godeps/Godeps.json, plugins/ipam/dhcp/daemon.go, vendor/github.com/coreos/go-systemd/NOTICE, vendor/github.com/coreos/go-systemd/activation/files.go, vendor/github.com/coreos/go-systemd/activation/listeners.go, vendor/github.com/coreos/go-systemd/activation/packetconns.go
This updates vendored go-systemd to v17, see https://github.com/coreos/go-systemd/releases/tag/v17.
It also contains a minor code fix to adapt to the new library.
=> vendor: bump go-systemd to v17

Godeps/Godeps.json, pkg/ipam/ipam.go, plugins/ipam/dhcp/main.go, plugins/ipam/host-local/main.go, plugins/ipam/static/main.go, plugins/main/bridge/bridge.go, plugins/main/host-device/host-device.go, plugins/main/ipvlan/ipvlan.go, plugins/main/loopback/loopback.go, plugins/main/loopback/loopback_test.go, plugins/main/macvlan/macvlan.go, plugins/main/ptp/ptp.go, plugins/main/vlan/vlan.go, plugins/meta/bandwidth/bandwidth_linux_test.go, plugins/meta/bandwidth/main.go, plugins/meta/flannel/flannel.go, plugins/meta/portmap/main.go, plugins/meta/tuning/tuning.go, plugins/sample/main.go, vendor/github.com/containernetworking/cni/libcni/api.go, vendor/github.com/containernetworking/cni/libcni/conf.go, vendor/github.com/containernetworking/cni/pkg/invoke/delegate.go, vendor/github.com/containernetworking/cni/pkg/invoke/exec.go, vendor/github.com/containernetworking/cni/pkg/invoke/raw_exec.go, vendor/github.com/containernetworking/cni/pkg/skel/skel.go, vendor/github.com/containernetworking/cni/pkg/types/current/types.go, vendor/github.com/containernetworking/cni/pkg/types/types.go, vendor/github.com/containernetworking/cni/pkg/version/plugin.go, vendor/github.com/containernetworking/cni/pkg/version/version.go
This picks up the skel changes for GET and plugin version info.
This PR will make CI red. However, now we can work on making each plugin support GET in parallel.
=> vendor: update cni to v0.7.0-alpha1

plugins/ipam/host-local/backend/allocator/config_test.go, plugins/ipam/host-local/backend/allocator/range.go, plugins/ipam/host-local/backend/allocator/range_test.go, plugins/ipam/host-local/host_local_test.go
Allocation code assumes the specified subnet is a clean network address
prefix, so check that is the case and throw an error otherwise
Fixes #161
=> plugins/host-local: ensure subnet is a network address

plugins/meta/bandwidth/bandwidth_linux_test.go, plugins/meta/bandwidth/ifb_creator.go
According to [iproute2](https://github.com/hustcat/iproute2/blob/master/tc/q_tbf.c#L93), we should calculate the buffer in bytes for `rate` and `burst` both. But the current `burs`t is in bit unit.
=> Fix tc-tbf burst value in bytes

README.md
The loopback cni just link up the loopback interface.
It dont create the loopback interface.And the loopback interface is create by docker none network.
=> fix_loopback_readme

CONTRIBUTING.md, README.md
I noticed that CONTRIBUTING told you to read the README and the README didn't tell you at all.
=> Add build instructions

plugins/main/bridge/bridge.go, plugins/main/bridge/bridge_test.go
In case of error ip addresses are not being released and hence there is a possible leakage.
=> bridge: release IP in case of error

plugins/meta/bandwidth/README.md, plugins/meta/bandwidth/main.go
Replace Kbps with bps and Kb with bits in bandwidth description.
=> Correct the bandwidth unit in description

Godeps/Godeps.json, vendor/github.com/coreos/go-iptables/NOTICE, vendor/github.com/coreos/go-iptables/iptables/iptables.go
This reverts commit 19f2f28178aa88772f69c4eeb3793d4a63c244b0, reversing
changes made to 72b62babeeb3d7b25c9809ea9eb9fc9c02cc0f71.
In other words, undo all the go-iptables madness and bring us back to where we were with v0.7.1
=> Revert "Merge pull request #180 from squeed/v0.7-bump-iptables"

pkg/ip/ipforward_linux_test.go, pkg/ns/ns_linux_test.go, plugins/ipam/dhcp/dhcp_test.go, plugins/main/bridge/bridge_test.go, plugins/meta/bandwidth/bandwidth_suite_test.go, plugins/meta/portmap/chain_test.go
Fix all ineffectual assignments to `err` variables which are not followed by error check.
=> Add missing error checks

plugins/meta/tuning/README.md, plugins/meta/tuning/tuning_test.go
This diff adds documents for #177 change (mac/mtu/promisc) in tuning README.md. Fixes #199.
=> Add description for mac/mtu/promisc in tuning README.md

plugins/ipam/static/README.md, plugins/ipam/static/main.go, plugins/ipam/static/static_suite_test.go, plugins/ipam/static/static_test.go
This change is to add CNI_ARGS support in static IPAM plugin.
When IP/SUBNET/GATEWAY are given in CNI_ARGS, static IPAM adds
these info in addition to config files.
To configure ip address only from CNI_ARGS, 'address' field in config
is changed to optional from required.
=> Support CNI_ARGS in static IPAM plugin

plugins/ipam/host-local/backend/allocator/allocator.go, plugins/ipam/host-local/backend/allocator/allocator_test.go, plugins/ipam/host-local/backend/disk/backend.go, plugins/ipam/host-local/backend/store.go, plugins/ipam/host-local/backend/testing/fake_store.go, plugins/ipam/host-local/host_local_test.go, plugins/ipam/host-local/main.go
host-local: add ifname to file tracking IP address used 
Obtain ifname from CmdArgs and pass to backend 
In the file tracking the IP address in use, add ifname to the line after ContainerID
Update host-local tests to use ifname along with ContainerID in storage file
Fixes #164
=> host-local: add ifname to file tracking IP address used 

plugins/main/host-device/host-device.go, plugins/main/loopback/loopback.go
Fixes https://github.com/containernetworking/plugins/issues/210.
Conform to new CNI spec https://github.com/containernetworking/cni/commit/23a5d8e617027c87a84605426c3b228931c69826.
Signed-off-by: Lantao Liu <lantaol@google.com>
=> Handle empty netns in DEL for `loopback` and `host-device`.

.travis.yml, Vagrantfile
stop testing on Go 1.9, start testing on Go 1.11
see also https://github.com/containernetworking/cni/pull/592
=> bump travis and vagrantfile to go 1.11

plugins/main/host-device/host-device.go, plugins/main/host-device/host-device_test.go
Refer to the issue #184 
- Support the IPAM options in the host-device
- Skip the IPAM function if it doesn't exist in the config (compatibility)
- Change the variable style from ALL_CAPS to CamelCase
- Also add the test case to test the IPAM with static module
- Check the IP address in the container should be same as what we set in the config.
=> Support the IPAM in the host-device

README.md, plugins/main/host-device/README.md, plugins/main/macvlan/README.md
=> fix the typo of macvlan and also modify documents to meet the current plugins.

plugins/main/bridge/README.md, plugins/main/bridge/bridge.go, plugins/main/bridge/bridge_test.go
This PR Change the bridge plugin to allow empty IPAM.
When the IPAM dictionary is empty the bridge plugin will connect a pure L2 interface(without any IP address on the interface) from the pod to a bridge on the host.
This PR will allow containers and everything running on top of them to have a pure L2 interface connected to a bridge. This can be useful for use cases of sniffing, running dhclient, give the pod a trunk interface, etc..
=> L2 bridge Implementation

pkg/ns/README.md, plugins/ipam/dhcp/client.go, vendor/github.com/d2g/dhcp4client/client.go
Fix some spelling errors:
1. "namepaces" to "namespace".
2. "essentialy" to "essentially".
3. "Sucessfull" to "Successful".
=> Fix some spelling errors

plugins/main/host-device/README.md
host-device's README.md missing 'type' field, so this change
just adds 'type' in config example.
=> Fix host-device README.md

OWNERS.md, plugins/main/windows/CONTRIBUTORS.md
Adding contributors.md for historical credit of Windows plugins and ownership for CNI plugins (copied from [MAINTAINERS](https://github.com/containernetworking/cni/blob/master/MAINTAINERS) file).
If there is a desired format or I missed/included anyone that I shouldn't have, let me know.
=> Added CONTRIBUTORS.md for Windows and CNI plugins OWNERS.md

plugins/ipam/dhcp/lease.go
Without setting this, the default route is missing in the containers. This is related to #192
=> some DHCP servers expect to request for explicit router options

README.md, plugins/meta/sbr/README.md, plugins/meta/sbr/main.go, plugins/meta/sbr/sbr_linux_test.go, plugins/meta/sbr/sbr_suite_test.go
This creates a new plugin (sbr) which sets up source based routing, for use
as a chained plugin for multi-network environments.
*Note to maintainers - this is now updated with tests etc. so should be ready to merge. I think I have addressed all comments so far.*
=> Create new Source Based Routing plugin

plugins/ipam/host-local/backend/allocator/config.go, plugins/ipam/static/main.go, plugins/meta/portmap/chain.go
Because these package names are short and they are unique, it can not conflict. So the import aliases that can be omitted and we should remove them.
=> Fix redundant import alias

plugins/meta/portmap/chain.go, plugins/meta/portmap/chain_test.go, plugins/meta/portmap/portmap.go, plugins/meta/portmap/portmap_integ_test.go, plugins/meta/portmap/portmap_test.go
This means that portmapped connections can be more easily controlled / firewalled.
=> Portmap: append, rather than prepend, entry rules

plugins/ipam/dhcp/systemd/cni-dhcp.service, plugins/ipam/dhcp/systemd/cni-dhcp.socket
This changes to add sample systemd unit files to activate socket with systemd. Fix #156.
=> Add systemd unit file to activate socket with systemd

pkg/hns/endpoint_windows.go, pkg/hns/netconf_windows.go, plugins/main/windows/win-bridge/README.md, plugins/main/windows/win-bridge/win-bridge_windows.go, plugins/main/windows/win-overlay/README.md, plugins/main/windows/win-overlay/win-overlay_windows.go
This adds the dns capability for supplying a runtime dnsConfig from a CRI. It also includes a bug fix for removing an endpoint when no IPAM is supplied.
=> Windows: Add runtime DNS and del bug fix

pkg/ip/utils_linux.go, pkg/ipam/ipam.go, pkg/testutils/cmd.go, plugins/ipam/dhcp/main.go, plugins/ipam/host-local/backend/disk/backend.go, plugins/ipam/host-local/main.go, plugins/ipam/static/main.go, plugins/main/bridge/bridge.go, plugins/main/bridge/bridge_test.go, plugins/main/host-device/host-device.go, plugins/main/host-device/host-device_test.go, plugins/main/ipvlan/ipvlan.go, plugins/main/ipvlan/ipvlan_test.go, plugins/main/loopback/loopback.go, plugins/main/macvlan/macvlan.go, plugins/main/macvlan/macvlan_test.go, plugins/main/ptp/ptp.go, plugins/main/ptp/ptp_test.go, plugins/main/vlan/vlan.go, plugins/main/vlan/vlan_test.go, plugins/meta/bandwidth/bandwidth_linux_test.go, plugins/meta/bandwidth/main.go, plugins/meta/portmap/chain.go, plugins/meta/portmap/main.go, plugins/meta/portmap/portmap.go, plugins/meta/portmap/portmap_test.go, plugins/meta/tuning/tuning.go, plugins/meta/tuning/tuning_test.go
Add check support for: 
bridge, ipvlan, macvlan, p2p, vlan and host-device main plugins
host-local and static ipam plugins
tuning, bandwidth and portmap meta plugins
Utility functions created for common PrevResult checking
Fixes #263
=> Add CHECK support for linux plugins

build_linux.sh, pkg/utils/buildversion/buildversion.go, plugins/ipam/dhcp/main.go, plugins/ipam/dhcp/options.go, plugins/ipam/dhcp/options_test.go, plugins/ipam/host-local/backend/allocator/config.go, plugins/ipam/host-local/backend/allocator/config_test.go, plugins/ipam/host-local/backend/allocator/range_set.go, plugins/ipam/host-local/main.go, plugins/ipam/static/main.go, plugins/main/bridge/bridge.go, plugins/main/host-device/host-device.go, plugins/main/ipvlan/ipvlan.go, plugins/main/loopback/loopback.go, plugins/main/macvlan/macvlan.go, plugins/main/ptp/ptp.go, plugins/main/vlan/vlan.go, plugins/main/windows/win-bridge/win-bridge_windows.go, plugins/main/windows/win-overlay/win-overlay_windows.go, plugins/meta/bandwidth/main.go, plugins/meta/firewall/firewall.go, plugins/meta/flannel/flannel.go, plugins/meta/portmap/main.go, plugins/meta/sbr/main.go, plugins/meta/tuning/tuning.go, plugins/sample/main.go, scripts/release.sh
Now that libcni has the ability to print a version message, plumb it through correctly.
While we're at it,
- fix import paths
- run gofmt
- add some more comments to sample
- add container runtime swappability for release
Fixes: #101
=> plugins: correctly output build version, cosmetic cleanups

plugins/main/host-device/host-device.go, plugins/main/macvlan/macvlan.go
This PR try to fix bug on IP revert if cmdAdd fails on macvlan and host-device plugin.
Function **ipam.ExecDel** will check whether CNI_COMMAND environment variable is **ADD**, if not, it will not work as expected. So when we want to revert IP allocation in cmdAdd with environment variable CNI_COMMAND equals to ADD, we have to change CNI_COMMAND to DEL temporarily, otherwise IP release will not succeed.
=> fix bug on ip revert if cmdAdd fails on macvlan and host-device

plugins/meta/sbr/main.go
Return nil instead of error for cmdCheck until support is added.
Fixes [296](https://github.com/containernetworking/plugins/issues/296)
=> Don't return error for cmdCheck() when support is not implemented

plugins/main/macvlan/README.md, plugins/main/macvlan/macvlan.go, plugins/main/macvlan/macvlan_test.go
To ease of config, make master config as optional parameter.
In default case, default route interface will be used for master.
=> macvlan: make master config as optional

pkg/hns/endpoint_windows.go
Upper and lowercase are both valid for window's GUIDs, so we need to honor that.
=> Windows: case insensitive compare for ids

plugins/meta/flannel/flannel.go
Currently we don't pass through the runtimeConfig from flannel down to the delegate call, I think it would be a good idea to do so.
=> Flannel: Pass through runtimeConfig to delegate

plugins/main/macvlan/README.md, plugins/main/macvlan/macvlan.go, plugins/main/macvlan/macvlan_test.go
This PR add the option to configure an empty ipam for the macvlan cni plugin.
When using the macvlan cni plugin with an empty ipam the requeted pod will get the macvlan interface but without any ip address.
One of the use cases for this feature is for projects that runs a dhcp server inside the pod like KubeVirt.
In KubeVirt we need to let the vm running inside the pod to make the dhcp request so it will be able to make a release an renew request when needed.
=> Allow to configure empty ipam for macvlan

Godeps/Godeps.json, pkg/ip/ipmasq_linux.go, plugins/main/ptp/README.md, vendor/github.com/coreos/go-iptables/iptables/iptables.go
ptp plugin : change source of ipmasq rule from ipn to ip
The old ipmasq rule's source is the whole subnet, this will cause all pods on the host will always hit the first masq chain. I think this may be confused.
The POSTROUTING chain of table nat is as follows, 
```
Chain POSTROUTING (policy ACCEPT 0 packets, 0 bytes)
pkts bytes target     prot opt in     out     source               destination         
2216  142K KUBE-POSTROUTING  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* kubernetes postrouting rules */
1867  118K CNI-3115be0572d3543649291916  all  --  *      *       172.17.0.64/26       0.0.0.0/0            /* name: "test" id: "a09b2aa6ab03415ee44b4065045437250d03939597514e608701bfd9045fce4c" */
0     0 CNI-832daee03b4f87f14a3870e7  all  --  *      * …
```
=> change source of ipmasq rule from ipn to ip

plugins/main/bridge/bridge.go, plugins/main/bridge/bridge_test.go
It looks like a change in #279 which seems to expect the exact address be passed into `SetupIPMasq` broke ip masquerading for the bridge plugin. See discussion [in that PR](https://github.com/containernetworking/plugins/pull/279#issuecomment-495828664) for more details.
This PR adds a ginkgo spec that reproduces the issue and a change to fix it.
=> bridge: fix ipMasq setup to use correct source address

plugins/meta/bandwidth/bandwidth_linux_test.go, plugins/meta/bandwidth/bandwidth_suite_test.go, plugins/meta/bandwidth/main.go
try to fix [https://github.com/containernetworking/plugins/issues/260](https://github.com/containernetworking/plugins/issues/260)
We should find the interface in host ns which bandwidth plugin works on through container interface instead of host interfaces, because host interfaces may contain multiple host-side veth interfaces, it's hard for us to judge.
=> bandwidth: get bandwidth interface in host ns through container interface

plugins/main/host-device/README.md, plugins/main/host-device/host-device.go, plugins/main/host-device/host-device_test.go
=> host-device: add pciBusID property

Godeps/Godeps.json, pkg/ipam/ipam.go, plugins/main/windows/win-bridge/win-bridge_windows.go, plugins/main/windows/win-overlay/win-overlay_windows.go, vendor/github.com/containernetworking/cni/libcni/api.go, vendor/github.com/containernetworking/cni/pkg/invoke/args.go, vendor/github.com/containernetworking/cni/pkg/invoke/delegate.go
ref to [https://github.com/containernetworking/plugins/issues/340](https://github.com/containernetworking/plugins/issues/340) and [https://github.com/containernetworking/plugins/issues/303](https://github.com/containernetworking/plugins/issues/303)
1. bump containernetworking/cni to v0.7.1
2. use delegateArgs in `ipam.ExecDel` instead of setting/unsetting environment
=> bump containernetworking/cni to v0.7.1

plugins/ipam/static/README.md, plugins/ipam/static/main.go, plugins/ipam/static/static_test.go, plugins/meta/tuning/README.md, plugins/meta/tuning/tuning.go, plugins/meta/tuning/tuning_test.go
This change introduces new capability flag to change MAC address
and to specify IP addresses by tuning and static.
=> Support ips capability in static and mac capability in tuning

pkg/ip/link_linux_test.go
on Linux 4.4 the syscall error message is "invalid argument" not "file exists"
=> pkg/ip unit test: be agnostic of Linux version

pkg/utils/utils.go, pkg/utils/utils_test.go, plugins/meta/bandwidth/bandwidth_linux_test.go, plugins/meta/bandwidth/main.go, plugins/meta/portmap/portmap.go, plugins/meta/portmap/utils.go
* Extract all hashing usage into `pkg/utils/hash` and refactored all usages
* Refactor duplication FormatChainName
* Fixes #347 
Co-authored-by: Cameron Moreau <cmoreau@pivotal.io>
cc @rosenhouse
=> Increase IfbDeviceName size and refactor hashing functions, fix

plugins/ipam/host-local/backend/allocator/allocator.go, plugins/ipam/host-local/backend/allocator/allocator_test.go, plugins/ipam/host-local/backend/disk/backend.go, plugins/ipam/host-local/backend/store.go, plugins/ipam/host-local/backend/testing/fake_store.go, plugins/ipam/host-local/host_local_test.go
try to fix [https://github.com/containernetworking/plugins/issues/327](https://github.com/containernetworking/plugins/issues/327)
=> host-local support idempotent allocation

pkg/hns/endpoint_windows.go, pkg/hns/netconf_windows.go, plugins/main/windows/win-bridge/README.md, plugins/main/windows/win-bridge/sample.conf, plugins/main/windows/win-bridge/win-bridge_windows.go, plugins/main/windows/win-overlay/README.md, plugins/main/windows/win-overlay/win-overlay_windows.go
Two seperate items here. The first adds an optional feature to easily allow for loopback dsr. The second relaxes the network type requirement to allow l2tunnel networks to be used with the l2bridge plugin.
=> Loopback dsr & L2Tunnel

plugins/main/host-device/host-device.go, plugins/main/host-device/host-device_test.go
If moving device to host network namespace fails, the retries will always fail because the interface with name **ifName** does not exist anymore, so we have to revert name setting, to make retires idempotent.
=> host-device: revert name setting to make retries idempotent

plugins/main/bridge/bridge.go
For https://github.com/containerd/containerd/issues/3507.
When multiple pods are started at the same time at the node startup, the `cni0` bridge may be attempted to create by multiple goroutines.
The bridge creation [handled `syscall.EEXIST`](https://github.com/containernetworking/plugins/blob/v0.7.5/plugins/main/bridge/bridge.go#L222), thus no problem there. However, the bridge address assignment doesn't handle this concurrency properly. https://github.com/containernetworking/plugins/blob/v0.7.5/plugins/main/bridge/bridge.go#L143
This can cause pod start failure with error `failed to set bridge addr: could not add IP address to \"cni0\": file exists`.
This PR handles `syscall.EEXIST` for address assignment, which should fix the problem.
/cc @cadmuxe 
Signed-off-by: Lantao Liu …
=> Fix: failed to set bridge addr: could not add IP address to \"cni0\": file exists

plugins/main/bridge/bridge.go
Backport https://github.com/containernetworking/plugins/pull/366 to 0.7 branch.
=> [Backport v0.7] Fix: failed to set bridge addr: could not add IP address to \"cni0\": file exists

plugins/main/bridge/bridge_test.go, plugins/main/host-device/host-device_test.go, plugins/main/ipvlan/ipvlan_test.go, plugins/main/loopback/loopback_test.go, plugins/main/macvlan/macvlan_test.go, plugins/main/ptp/ptp_test.go, plugins/main/vlan/vlan_test.go
Fixes #342, please also reference #373
=> Fixes #342, cleanup netns after test suite

plugins/meta/portmap/portmap.go
Fix for issue #378, where when in a dual-stack environment specifying a hostIP would cause an error during container creation.
=> Fix dual-stack support in meta/portmap

plugins/main/loopback/loopback.go, plugins/main/loopback/loopback_test.go
When prevResults are not returned to loopback plugin, create results to return based on the lo interface and IP address assigned inside container. 
Fixes [381](https://github.com/containernetworking/plugins/issues/381)
=> When prevResults are not supplied to loopback plugin, create results to return

pkg/testutils/dns.go, plugins/main/ptp/ptp.go, plugins/main/ptp/ptp_test.go
Previously, if an IPAM plugin provided DNS settings in the result to the PTP
plugin, those settings were always lost because the PTP plugin would always
provide its own DNS settings in the result even if the PTP plugin was not
configured with any DNS settings.
This was especially problematic when trying to use, for example, the host-local
IPAM plugin's support for retrieving DNS settings from a resolv.conf file on
the host. Before this change, those DNS settings were always lost when using the
PTP plugin and couldn't be specified as part of PTP instead because PTP does not
support parsing a resolv.conf file.
This change checks to see if any fields were actually set in the PTP plugin's
DNS settings and only overrides any previous DNS results from an IPAM plugin in
the case that settings …
=> ptp: only override DNS conf if DNS settings provided

plugins/meta/firewall/firewall.go
The CNI spec states that for DEL implementations, "when CNI_NETNS and/or
prevResult are not provided, the plugin should clean up as many resources as
possible (e.g. releasing IPAM allocations) and return a successful response".
This change results in the firewall plugin conforming to the spec by not
returning an error whenever the del method is not provided a prevResult.
Signed-off-by: Erik Sipsma <sipsma@amazon.com>
=> firewall: don't return error in DEL if prevResult is not found.

CONTRIBUTING.md
I found a description to install `cnitool` is missing in the current `CONTRIBUTING.md` while `cnitool` is necessary to be installed to run the tests.
=> contributing doc: describe cnitool installation

CONTRIBUTING.md
`test.sh` mentioned in CONTRIBUTING.md doesn't exist now as it was separated into two OS-specific scripts.
=> contributing doc: revise test script name to run

plugins/main/bridge/bridge.go, plugins/main/bridge/bridge_test.go, plugins/main/vlan/vlan.go
Check vlan id if in [0, 4094] when loading net conf to avoid unexpected error from kernel.
=> bridge: check vlan id when loading net conf

plugins/meta/bandwidth/bandwidth_linux_test.go, plugins/meta/bandwidth/ifb_creator.go, plugins/meta/bandwidth/main.go
This is the first out of several required PRs across CNI plugins, CRI-O and Kubelet.
We need to use something bigger than int as it goes only into 2Gb for rate and burst, which is not enough for 10Gbps networking anymore.
Since we use bits in JSON and can feed upto 4GByte into tbf (at least per current implementation), we need to use uint64 even for burst and then number check it for uint32 max * 8.
Thanks for looking into this
Ashley
=> Use uint64 for Bandwidth plugin

plugins/main/macvlan/README.md, plugins/main/macvlan/macvlan.go
Try to fix #393 
If we want to create a macvlan interface from a parent(master) interface with a greater MTU, it will fail by kernel like below. And the error message is `Invalid argument` which contains no useful information. So we should add a MTU validation before creating interface in kernel.
```
[root@test ~]# ip link show eth2
11: eth2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000
link/ether fa:f2:3b:5a:33:02 brd ff:ff:ff:ff:ff:ff
[root@test ~]# ip link add link eth2 macv1 mtu 2000 type macvlan
RTNETLINK answers: Invalid argument
[root@test ~]# ip link add link eth2 macv1 mtu 1200 type macvlan
[root@test ~]# ip link show macv1
13: macv1@eth2: <BROADCAST,MULTICAST> mtu 1200 qdisc noop state DOWN mode DEFAULT group default …
```
=> macvlan: add MTU validation to loadNetConf

plugins/meta/tuning/tuning.go
This change sends gratuitous ARP when MAC address is changed to
let other devices to know the MAC address update.
=> Sending GratuitousArp in case of MAC address update

.travis.yml, pkg/testutils/netns_linux.go, test_linux.sh
When running in a user namespace created by an unprivileged user the
owner of /var/run will be reported as the unknown user (as defined in
/proc/sys/kernel/overflowuid) so any access to the directory will
fail.
If the XDG_RUNTIME_DIR environment variable is set, check whether the
current user is also the owner of /var/run.  If the owner is different
than the current user, use the $XDG_RUNTIME_DIR/netns directory.
Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>
=> testutils: newNS() works in a rootless user namespace

plugins/ipam/static/README.md, plugins/ipam/static/main.go, plugins/ipam/static/static_test.go
This change introduce priorities for IPs input among CNI_ARGS, 'args' and runtimeConfig.
Fix #399
Signed-off-by: Tomofumi Hayashi <tohayash@redhat.com>
=> static: prioritize the input sources for IPs

plugins/main/vlan/vlan.go, plugins/main/vlan/vlan_test.go
Try to fix #393 
Same like #404 , vlan plugin has the same problem if we want to create a vlan interface from a parent(master) interface with greater MTU.
```
[root@test ~]# ip link show eth2
11: eth2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000
link/ether fa:f2:3b:5a:33:02 brd ff:ff:ff:ff:ff:ff
[root@test ~]# ip link add link eth2 name eth2.100 mtu 2000 type vlan id 100
RTNETLINK answers: Invalid argument
[root@test ~]# ip link add link eth2 name eth2.100 mtu 1200 type vlan id 100
[root@test ~]# ip link show eth2.100
15: eth2.100@eth2: <BROADCAST,MULTICAST> mtu 1200 qdisc noop state DOWN mode DEFAULT group default qlen 1000
link/ether fa:f2:3b:5a:33:02 brd ff:ff:ff:ff:ff:ff
```
=> vlan: add MTU validation to loadNetConf

pkg/utils/iptables.go, pkg/utils/iptables_test.go, plugins/meta/firewall/firewall_iptables_test.go, plugins/meta/firewall/iptables.go, plugins/meta/portmap/chain.go, plugins/meta/portmap/portmap.go
Concurrent use of the `portmap` and `firewall` plugins can result in errors during iptables chain creation:
- The `portmap` plugin has a time-of-check-time-of-use race where it checks for existence of the chain but the operation isn't atomic.
- The `firewall` plugin doesn't check for existing chains and just returns an error.
This commit makes both operations idempotent by creating the chain and then discarding the error if it's caused by the chain already existing. I've added a test for idempotent creation in the `firewall` plugin but the `portmap` plugin already had one so I've left that in place.
=> ensure iptables chain creation is idempotent

go.mod, go.sum, pkg/utils/iptables.go, pkg/utils/iptables_test.go, plugins/meta/portmap/chain.go, plugins/meta/portmap/chain_test.go, plugins/meta/portmap/portmap_integ_test.go, vendor/github.com/coreos/go-iptables/iptables/iptables.go, vendor/modules.txt
It turns out that the portmap plugin is not idempotent if its executed in parallel.
The errors are caused due to a race of different instantiations deleting the chains.
This patch does that the portmap plugin doesn't fail if the errors are because the chain doesn't exist on teardown.
xref: https://github.com/containernetworking/plugins/issues/418
Signed-off-by: Antonio Ojea <antonio.ojea.garcia@gmail.com>
=> Portmap doesn't fail if chain doesn't exist

plugins/main/bridge/README.md
The `cniVersion` field was missing in the network configuration of one of the examples of the 'bridge' plugin. Also fixed the indentation.
Omitting `cniVersion` results in the following kubelet error:
```
Dec 18 10:58:30 my-k8s-master kubelet[14847]: W1218 10:58:30.629078   14847 cni.go:202] Error validating CNI config list {"cniVersion":"", ... }: [plugin bridge does not support config version ""]
```
=> bridge: add missing cniVersion in README example

.travis.yml, scripts/release.sh
Added mips64le support for releasing plugins. 
Since the golang has a native support for cross compiling for mips64le, the plugins which written in pure go should have a completely support for mips64le.
=> add support for mips64le

plugins/main/bridge/bridge.go
If the Linux kernel is not built with the parameter CONFIG_BRIDGE_VLAN_FILTERING, passing `vlanFiltering` in the Bridge struct returns an error creating the bridge interface. This happens even when no parameter is set on `Vlan` in the CNI config.
This change fixes the case where no `Vlan` parameter is configured on CNI config file so the flag doesn't need to be included in the struct.
Addresses problems related in issue #370 seen on the Raspberry Pi kernel.
Cc. @alexellis
=> Fix for the case where kernel doesn't have CONFIG_BRIDGE_VLAN_FILTERING

plugins/main/vlan/vlan.go, plugins/main/vlan/vlan_test.go
DEL can be called multiple times, a plugin should return no error if
the device is already removed, and other errors should be returned. It
was the opposite for vlan plugin. This PR fixes it.
=> Fix vlan plugin returning error when device is already removed

plugins/main/loopback/loopback.go
Fixes a minor bug in loopback plugin. The IPv6 address check loops over IPv4 addresses.
I'm not quite sure what value these address checks provide, but if we are going to do it let's at least do it right.
Test suite passes successfully.
=> loopback: Fix ipv6 address checks

pkg/ip/link_linux.go
Error message is untrusty.
From [https://github.com/vishvananda/netlink/commit/99091d844046e6b17e4b094e937e8e9254afbfbd](https://github.com/vishvananda/netlink/commit/99091d844046e6b17e4b094e937e8e9254afbfbd) and codes, we can see that there are three kinds of error message about **not found**
- ```Link %s not found```
- ```Link alias %s not found```
- ```Link not found```
Our judgment will obviously fail in some cases, and type cast to `LinkNotFoundError` is more proper to help distinguish **not found error** from others.
=> pkg/ip: use type cast instead of untrusty error message

plugins/main/ptp/ptp.go
remove some redundant lines against [https://github.com/containernetworking/plugins/blob/832f2699c29cd6614535b91b11acdecda6d867c1/plugins/main/ptp/ptp.go#L84](https://github.com/containernetworking/plugins/blob/832f2699c29cd6614535b91b11acdecda6d867c1/plugins/main/ptp/ptp.go#L84)
=> ptp: remove some redundant lines

pkg/utils/sysctl/sysctl_linux.go, pkg/utils/sysctl/sysctl_linux_test.go
A follow-up fix PR of #437 , we should use black-box testing for utility functions.
BTW, fix some typo in comments.
=> pkg/utils: sysctl package should use black-box testing

plugins/main/host-device/host-device.go
In case pciBusID contains pci address of the virtio device, then lookup `ip link` under `{sysBusPCIDir}/virtio{id}/net` directory.
Issue: https://github.com/containernetworking/plugins/issues/320
Signed-off-by: Periyasamy Palanisamy <periyasamy.palanisamy@est.tech>
=> Make host-device to work with virtio net device

OWNERS.md
Add Michael Cambria per https://github.com/containernetworking/cni/pull/751
Remove Stefan Junker per personal request
Update Casey's email to @redhat.com
=> owners: updates for maintainer changes

pkg/ns/ns_linux.go
The current ns package code is very careful about not leaving the calling
thread with the overridden namespace set, for example when origns.Set() fails.
This is achieved by starting a new green thread, locking its OS thread, and
never unlocking it. Which makes golang runtime to scrap the OS thread backing
the green thread after the go routine exits.
While this works, it's probably not as optimal: stopping and starting a new OS
thread is expensive and may be avoided if we unlock the thread after resetting
network namespace to the original. On the other hand, if resetting fails, it's
better to leave the thread locked and die.
While it won't work in all cases, we can still make an attempt to reuse the OS
thread when resetting the namespace succeeds. This can be achieved by unlocking
the …
=> Unlock OS thread after netns is restored

plugins/main/bridge/bridge.go
fix #463
link host veth pair to bridge, the Initial state
of port is BR_STATE_DISABLED and change to
BR_STATE_FORWARDING async.
=> check bridge's port state

pkg/hns/netconf_windows.go, pkg/hns/netconf_windows_test.go, plugins/main/windows/win-bridge/README.md, plugins/main/windows/win-bridge/win-bridge_windows.go
If the pluging receives portMappings in runtimeConfig, the pluing will add a NAT policy for each port mapping on the generated endpoints.
It enables HostPort usage on Windows with win-bridge (currently silently ignored).
Requires Windows >=1903 for containers to reach their own node through NodeIP + HostPort.
=> win-bridge: add support for portMappings capability

plugins/meta/portmap/README.md, plugins/meta/portmap/main.go, plugins/meta/portmap/portmap.go, plugins/meta/portmap/portmap_test.go
The DNAT hairpin rule only allow the container itself to access the ports it is exposing thru the host IP. Other containers in the same subnet might also want to access this service via the host IP, so apply this rule to the whole subnet instead of just for the container.
This is particularly useful with setups using a reverse proxy for https. With such a setup connections between containers (for ex. oauth2) have to downgrade to http, or need complex dns setup to make
use of the internal IP of the reverse proxy. On the other hand going thru the host IP is easy as that is probably what the service name already resolve to.
=> portmap: Apply the DNAT hairpin to the whole subnet

plugins/meta/sbr/main.go
A /64 mask was used which routed an entire cidr based on source, not only the bound address.
Fixes #478
=> plugins/meta/sbr: Adjusted ipv6 address mask to /128

OWNERS.md, plugins/meta/flannel/README.md
Signed-off-by: root <timyinshi>
the error url is:
https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/container-networking
the right url is:
https://docs.microsoft.com/en-us/virtualization/windowscontainers/container-networking/architecture
=> modify the error url of windowscontainer

pkg/ip/link_linux.go, plugins/main/bridge/bridge.go
The interface plugins should have absolute control over their addressing and routing.
=> ptp, bridge: disable accept_ra on the host-side interface

plugins/main/macvlan/macvlan.go, plugins/main/macvlan/macvlan_test.go
This change sets the mac address if specified during the creation of the
macvlan interface. This is superior to setting it via the tuning plugin
because this ensures the mac address is set before an IP is set,
allowing a container to get a reserved IP address from DHCP.
Related #450
=> macvlan: set mac address from args

plugins/main/host-device/host-device.go
When trying to move a master and slave interface into a container it is not possible without first bringing the interfaces down. This change ensures that the interface is set to down prior to trying to move the interface into the container. This matches the behaviour on moving an interface out of the container.
=> host-device: Bring interfaces down before moving.

plugins/meta/portmap/portmap.go, plugins/meta/portmap/portmap_test.go
It may happen that you want to map a port only in one IP family.
It can be achieved using the unspecified IP address of the
corresponding IP family as HostIP i.e.:
podman run --rm --name some-nginx -d -p 0.0.0.0:8080:80 nginx
The problem is that current implementation considers the
unspecified address valid and appends it to the iptables rule:
-A CNI-DN-60380cb3197c5457ed6ba -s 10.88.0.0/16
-d 0.0.0.0/32 -p tcp -m tcp --dport 8080 -j CNI-HOSTPORT-SETMARK
This rule is not forwarding the traffic to the corresponding port.
We should use the unspecified address only to discriminate the IP
family of the port mapping, but not use it to filter the dst.
=> portmap: don't use unspecified address as iptables rule destination 

plugins/ipam/dhcp/daemon.go, plugins/ipam/dhcp/lease.go
Resolve issue #470 
when  stp is turned on the bride,the stp is taking too long to reslove .
There was no need to increase  the  dhcpclinet timeout, dhcp can resolve within  5 secs,so I increased  the BackOff retry to max of 62 secs , this seems to resolve the issue .
```
2020/06/18 16:29:07 9db6dae0076326ec96fb4b6e85261e761fd1758527d7245169c40bd5a284a858/dhcp-pod-bridge-conf/net1: acquiring lease
2020/06/18 16:29:12 no DHCP packet received within 5s
2020/06/18 16:29:12 retrying in 4.881018 seconds
2020/06/18 16:29:18 b72f9e75838eee52914bbf2933f1d4c5175e9c6420459fd115390ac37b3abf8e/dhcp-pod-bridge-conf/net1: acquiring lease
2020/06/18 16:29:22 no DHCP packet received within 5s
2020/06/18 16:29:22 retrying in 8.329120 seconds
2020/06/18 16:29:23 no DHCP packet received within 5s
2020/06/18 …
```
=> Fix handling of delay in acquiring lease with stp turned on

plugins/meta/firewall/iptables.go
Wrong function was called which resulted in the wrong chain comment. But no functional difference.
=> firewall: fix generate of admin chain comment

plugins/meta/portmap/main.go
The portmap plugin, once receives a DEL, tries to delete as much as possible.
This causes issues on busy environment, because all DEL command are going to be processed by the portmap plugin, that will perform iptables operations holding the lock despite it doesn't have anything to delete.
portmap should only try to delete if it receives portMap parameters from the runtimeConfig.
xref: https://github.com/kubernetes/kubernetes/pull/92811#issuecomment-657426111
Fixes: https://github.com/containernetworking/plugins/issues/510
Signed-off-by: Antonio Ojea <aojea@redhat.com>
=> portmap should not perform deletions if not portMapping config received

plugins/meta/firewall/README.md
When preparing the slides of CNI Deep Dive, found these typos in firewall plugin docs.
Most of them are just small typos, but the last two lines are fatal I think.
=> firewall: fix some typos in docs

README.md
Inspired by https://github.com/containernetworking/cni/pull/780, but I had to add the non-security info too.
Interesting the maintainers file has a different name here.
=> Add contact info

pkg/ns/ns_linux.go, pkg/ns/ns_linux_test.go
In GetCurrentNS, If there is a context-switch between
getCurrentThreadNetNSPath and GetNS, another goroutine may execute in
the original thread and change its network namespace, then the original
goroutine would get the updated network namespace, which could lead to
unexpected behavior, especially when GetCurrentNS is used to get the
host network namespace in netNS.Do.
The added test has a chance to reproduce it with "-count=50".
The patch fixes it by locking the thread in GetCurrentNS.
Fixes #524
=> Fix race condition in GetCurrentNS

plugins/meta/flannel/flannel.go, plugins/meta/flannel/flannel_linux.go, plugins/meta/flannel/flannel_windows.go
`consumeScratchNetConf` will remove net conf file in defer, so if `invoke.DelegateDel` fails and CNI DEL is called again, it will always be successful because net conf file has been removed already.
So I think the better way is to remove net conf file after `invoke.DelegateDel` succeed, this will make sure the CNI DEL retry will go through `invoke.DelegateDel` every time.
=> flannel: remove net conf file after DEL succeed

plugins/main/ipvlan/README.md, plugins/main/ipvlan/ipvlan.go, plugins/main/ipvlan/ipvlan_test.go
This change makes ipvlan master parameter optional.
Default to default route interface as macvlan does.
=> ipvlan: make master config as optional

plugins/meta/flannel/README.md, plugins/meta/flannel/flannel.go, plugins/meta/flannel/flannel_linux.go, plugins/meta/flannel/flannel_linux_test.go
(NOTE: This work started under PR #527 which was a combination of this and the addition of logging; now split into 2 PRs)
This change allows providing an 'ipam' section as part of the input network configuration for flannel. It is then used as basis to construct the ipam parameters provided to the delegate.
All parameters from the input ipam are preserved except:
* 'subnet' which is set to the flannel host subnet
* 'routes' which is complemented by a route to the flannel network.
One use case of this feature is to allow adding back the routes to the cluster services and/or to the hosts (HostPort) when using isDefaultGateway=false. In that case, the bridge plugin does not install a default route and, as a result, only pod-to-pod connectivity would be available.
Example:
```
{
"name": …
```
=> flannel: allow input ipam parameters as basis for delegate

plugins/meta/vrf/vrf_test.go
This is based on https://github.com/containernetworking/plugins/pull/525, trying to limit the size of the PRs.
The new tests expand coverage, checking deletion, ip address handling,
0.4.0 compatibility, behaviour in case of multiple vrfs.
=> VRF CNI: Additional tests

plugins/ipam/dhcp/README.md
The current cni config has an extra comma and cannot be parsed normally, the kubelet will report an error as follows:
"Error loading CNI config file: error parsing configuration: invalid character '}' looking for beginning of object key string"
=> dhcp: fix example configuration

plugins/meta/vrf/main.go
The e2e tests already covers both versions, and since the plugin is meant to be used in chains, this will augment the scope of the plugins it can be used with.
=> VRF: extend supported version to 0.3.1 too

plugins/meta/vrf/README.md, plugins/meta/vrf/main.go, plugins/meta/vrf/vrf.go, plugins/meta/vrf/vrf_test.go
When specified from the user, the VRF will get assigned to the given tableid instead of having the CNI to choose for a free one.
This is based on https://github.com/containernetworking/plugins/pull/535 and https://github.com/containernetworking/plugins/pull/525
=> VRF CNI: Add an optional table parameter.

plugins/main/bridge/bridge_test.go
Instead of checking the total number of addresses, which might vary
depending on the IPv6 Privacy Address settings of the distro being
used, just check that we have the number of non-link-local addresses
we expect.
@containernetworking/cni-maintainers @squeed
=> bridge: fix testcase to check addresses we care about

go.mod, go.sum, vendor/github.com/coreos/go-iptables/iptables/iptables.go, vendor/modules.txt
Closes #544
The above issue describes a situation where using the bridge plugin with IPv6 addresses prevented `DEL` from working correctly.
`DEL` seems to be failing in the body of `TeardownIPMasq`
This arises because:
* twice delete postrouting rules: `ipn.String()` `ipn.IP.String()` #279
* we are using a version of go-iptables which is bugged for v6
PR coreos/go-iptables/pull/74 describes why this does not work. The error message is not being checked correctly.
Using a later version of go-iptables means that
* when the second `ipt.Delete` fails (this is okay)
* we will correctly interpret this as an non-fatal error
* `TeardownIPMasq` will not prematurely exit the method
* `ipt.ClearChain` now can run
* `ipt.DeleteChain` now can run
This explains why this was working for v4 but not v6
-- …
=> deps: bump coreos/go-iptables

plugins/main/vlan/vlan.go
At the moment error messages generated during execution of delegate IPAM plugin are indistinguishable from main `vlan` messages leading to cryptic messages like `no plugin name provided` which IS hard to debug from a human operator level.
This PR fixes that behavior.
=> [main/vlan] Fix error handling for delegate IPAM plugin

plugins/main/host-device/host-device.go
This commit would make host-device plugin as a placeholder
for DPDK device when applications wants to attach it with
a pod container through network attachment definition.
Signed-off-by: Periyasamy Palanisamy <periyasamy.palanisamy@est.tech>
=> host-device: Add support for DPDK device

plugins/main/vlan/vlan.go
Fixing a few error messages that the vlan plugin returns. These appear to be mistaken references to the ptp plugin.
=> vlan: fix error message text by removing ptp references

plugins/ipam/dhcp/daemon.go, plugins/ipam/dhcp/lease.go, plugins/ipam/dhcp/main.go
What
----
Addresses #470, albeit quite naively. Building on the existing daemon configuration code
A user would deploy the daemon (using the systemd example):
```
[Service]
ExecStart=/opt/cni/bin/dhcp daemon -timeout 15s
```
to configure the DHCP client timeout to 15s. The default timeout remains 5s unchanged.
Why
---
If a user configures their DHCP daemon, because they are in an environment where DHCP responses may take a long time, an IP address will still be allocated for their container
Why not
---
It is arguable that a simpler solution would be to arbitrarily increase the default timeout to 15s. I can redo this PR to do that instead
Further work
------------
If this is merged I will make a cni.dev PR to document the CLI option, consistent with `hostprefix` and friends
=> DHCP timeout is configurable

plugins/meta/flannel/flannel.go, plugins/meta/flannel/flannel_linux.go, plugins/meta/flannel/flannel_linux_test.go
It support three mode for ip stack allocation now:
1. only ipv4 stack allocation, `subnet.env` configuration like following:
```
FLANNEL_NETWORK=172.16.0.0/16
FLANNEL_SUBNET=172.16.0.1/24
FLANNEL_MTU=1450
FLANNEL_IPMASQ=true
```
It's compatible with origin single only ipv4 ip stack allocation.
2. only ipv6 stack allocation,  `subnet.env` configuration like following:
```
FLANNEL_IPV6_NETWORK=fc00::/48
FLANNEL_IPV6_SUBNET=fc00::1/64
FLANNEL_MTU=1450
FLANNEL_IPMASQ=true
```
3. dual stack ip allocation,  `subnet.env` configuration like following:
```
FLANNEL_NETWORK=172.16.0.0/16
FLANNEL_SUBNET=172.16.0.1/24
FLANNEL_IPV6_NETWORK=fc00::/48
FLANNEL_IPV6_SUBNET=fc00::1/64
FLANNEL_MTU=1450
FLANNEL_IPMASQ=true
```
=> add flannel cni to support dual stack ip allocation

plugins/main/macvlan/macvlan.go
The original issue was: https://github.com/containernetworking/cni/issues/84
I've added "a fix" for it in
https://github.com/containernetworking/cni/pull/149 which then was
merged in https://github.com/containernetworking/cni/pull/177
The thing is that "the fix" was incorrect as it was setting 1 on
arp_proxy (I really don't recall why) instead of setting it on
arp_notify - which was my original suggestion in:
https://github.com/rkt/rkt/issues/1765#issuecomment-188776317
Setting apr_proxy can be harmfull and we have already support for
sending GratuitousArpOverIface after setting an IP address, so setting
any sysctl should not be needed.
Signed-off-by: Piotr Skamruk <piotr.skamruk@gmail.com>
=> [macvlan] Stop setting proxy-arp on macvlan interface

pkg/ipam/ipam_linux.go
Since the sysctl key syntax already uses the dot as separator, dots in interface names that appear in sysctl keys, as is the case for the net.ipv6.conf.<iface>.* entries, must be replaced by slashes.
=> pkg/ipam: convert dots to slashes in interface names for sysctl

plugins/main/windows/win-bridge/win-bridge_windows.go
fix a nil pointer panic while calling HNS API (V1) on win-bridge.
=> win-bridge: fix panic while calling HNS api

plugins/meta/portmap/portmap.go
Scanned the whole project based on #585  and found this left behind.
=> portmap: use slashes in sysctl template to support interface names which separated by dots

plugins/ipam/host-local/backend/allocator/allocator.go, plugins/ipam/host-local/backend/allocator/allocator_test.go
Ref to #579 , just try another way to fix the same issue. Here is the details [https://github.com/containernetworking/plugins/pull/579#issuecomment-772466664](https://github.com/containernetworking/plugins/pull/579#issuecomment-772466664).
Fixes #596
=> host-local: remove redundant startRange in RangeIterator to avoid mismatching with startIP

.github/workflows/test.yaml
The V2 offers: https://github.com/actions/setup-go#v2
- Adds GOBIN to the PATH
- Proxy Support
- stable input
- Bug Fixes (including issues around version matching and semver)
=> gha: update actions/setup-go@v2

plugins/ipam/static/main.go, plugins/ipam/static/static_test.go
I am writing my own ipam plugin for a little project I am working on and stumbled across this nil check that looked out of place.
Omitting the `"ipam"` key from the config, while still supplying args or `runtimeConfig` would resulting in a nil pointer panic.
Signed-off-by: Nico Schieder <nschieder@redhat.com>
=> Fix nil-pointer check

plugins/meta/tuning/tuning.go, plugins/meta/tuning/tuning_test.go
Since the CNI Spec bump to v1.0 the tuning plugin no longer updates the
mac address in the cni result for 0.4.0 or below configs. I don't think
this ever worked when the cni result was converted to a different version.
A test has been added to ensure it is working for all spec versions.
Fixes #605
=> tuning: always update MAC in CNI result

pkg/ip/ip.go, pkg/ip/ip_test.go, plugins/ipam/host-local/backend/allocator/config.go, plugins/ipam/host-local/backend/allocator/config_test.go
A new version of #416 , try to fix #411 
From the conclusion of [https://github.com/containernetworking/plugins/pull/416#discussion_r351387959](https://github.com/containernetworking/plugins/pull/416#discussion_r351387959), I've introduced a new type `IP` to support parsing format `<ip>[/<prefix>]`.
And I think this can also be used in `static` plugin.
=> host-local: support custom IPs allocation through runtime configuraton

plugins/ipam/host-local/backend/allocator/config.go, plugins/ipam/host-local/backend/allocator/config_test.go
ref to #411 
CNI convention said that `ip/prefix` is supported in [CNI args](https://github.com/containernetworking/cni/blob/master/CONVENTIONS.md#args-in-network-config), but unfortunately not, this PR is trying to fix this through a new internal way (CNI maintained [IP type](https://github.com/containernetworking/plugins/blob/master/pkg/ip/ip.go)). And `ip` in env args will support prefix through this, too.
=> host-local: support ip/prefix in env args and CNI args

plugins/meta/sbr/main.go, plugins/meta/sbr/sbr_linux_test.go
[sbr]: Use different tableID for every ipCfg    
Move default table routes which  match the ipCfg config
This allows SBR plugin to accommodate for multi-ip interfaces
Fixes #581 
Signed-off-by: Anurag Dwivedi <anuragensemble1@gmail.com>
=>  Add multi IP support for SBR

OWNERS.md
I am moving on from Weaveworks, and will not be working in the container networking domain.
=> Remove Bryan Boreham as maintainer

pkg/ip/link_linux.go, pkg/ip/link_linux_test.go, plugins/main/bridge/bridge.go, plugins/main/bridge/bridge_test.go, plugins/main/ptp/ptp.go
Controlling the mac address of the interface (veth peer) in the
container is useful for functionalities that depend on the mac address.
Examples range from dynamic IP allocations based on an identifier (the
mac) and up to firewall rules (e.g. no-mac-spoofing).
Enforcing a mac address at an early stage and not through a chained
plugin assures the configuration does not have wrong intermediate
configuration. This is especially critical when a dynamic IP may be
provided already in this period.
But it also has implications for future abilities that may land on the
bridge plugin, e.g. supporting no-mac-spoofing.
The field name used (`mac`) fits with other plugins which control the
mac address of the container interface.
The mac address may be specified through the following methods:
- CNI_ARGS …
=> bridge: Add mac field to specify container iface mac

pkg/ip/link_linux.go, pkg/ip/link_linux_test.go
Instead of moving the host side of the veth peer into the host
network namespace later, just create it in the host namespace
directly.
=> ip: place veth peer in host namspace directly

README.md
Better to update the CI badge on README as #555 replaced CI infra from Travis CI to GitHub Actions.
Signed-off-by: Takuya Noguchi <takninnovationresearch@gmail.com>
=> Update the CI badge from Travis CI to GitHub Actions

plugins/ipam/static/main.go, plugins/ipam/static/static_test.go
By wrapping the error msg we ended up actually duplicating the exact same msg `net.ParseCIDR` replies, as seen in its implementation - [0] & [1]
This PR makes the error msg less confusing.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1897431
[0] - https://github.com/golang/go/blob/2ebe77a2fda1ee9ff6fd9a3e08933ad1ebaea039/src/net/net.go#L540
[1] - https://github.com/golang/go/blob/2ebe77a2fda1ee9ff6fd9a3e08933ad1ebaea039/src/net/ip.go#L739
=> Fix confusing error msg invalid cidr

pkg/ip/link_linux.go, pkg/testutils/netns_linux.go
The current code accidentally ignores partial reads, since it doesn't
check the return value of (io.Reader).Read.
What we actually want is io.ReadFull(rand.Reader, buf), which is
conveniently provided by rand.Read(buf).
=> Use crypto/rand.Read, not crypto.Reader.Read

pkg/utils/sysctl/sysctl_linux.go, plugins/meta/tuning/tuning.go
filepath.Join is already specified to clean its output,
and the implementation indeed does so.
=> Don't redundantly filepath.Clean the output of filepath.Join

.github/workflows/test.yaml, go.mod, go.sum, pkg/link/link_suite_test.go, pkg/link/spoofcheck.go, pkg/link/spoofcheck_test.go, plugins/main/bridge/bridge.go, plugins/main/bridge/bridge_test.go, vendor/github.com/networkplumbing/go-nft/LICENSE, vendor/github.com/networkplumbing/go-nft/nft/chain.go, vendor/github.com/networkplumbing/go-nft/nft/config.go, vendor/github.com/networkplumbing/go-nft/nft/config/chain.go, vendor/github.com/networkplumbing/go-nft/nft/config/config.go, vendor/github.com/networkplumbing/go-nft/nft/config/rule.go, vendor/github.com/networkplumbing/go-nft/nft/config/table.go, vendor/github.com/networkplumbing/go-nft/nft/doc.go, vendor/github.com/networkplumbing/go-nft/nft/exec/exec.go, vendor/github.com/networkplumbing/go-nft/nft/rule.go, vendor/github.com/networkplumbing/go-nft/nft/schema/chain.go, vendor/github.com/networkplumbing/go-nft/nft/schema/rule.go, vendor/github.com/networkplumbing/go-nft/nft/schema/schema.go, vendor/github.com/networkplumbing/go-nft/nft/schema/table.go, vendor/github.com/networkplumbing/go-nft/nft/table.go, vendor/modules.txt
The new macspoofchk field is added to the bridge plugin to support
anti-mac-spoofing.
When the parameter is enabled, traffic is limited to the mac addresses
of the container interface (the veth peer that is placed in the
container ns).
The implementation is using nftables and should only be used on nodes
that support it.
Notes:
- ~~This change is under e2e and functional testing, confirming it works as expected beyond the existing integration tests.~~
- ~~The [go-nft ](https://github.com/EdDev/go-nft) used in this PR is not a tagged version. Post testing and documentation a tag will be added and the dependency updated.~~
=> bridge: Add macspoofchk support

plugins/main/ipvlan/ipvlan.go
This PR fixes the missing Gratuitous ARP functionality in the IPVLAN plugin.
The code is copied from the MACVLAN plugin: https://github.com/containernetworking/plugins/blob/e27c48b391539f5536918b9c379c59ef2793cb0d/plugins/main/macvlan/macvlan.go#L297-L311
Fixes #673
=> ipvlan: Send Gratuitous ARP after IPs are set

plugins/meta/tuning/tuning.go
=> Allow setting sysctls on a particular interface

plugins/ipam/dhcp/daemon.go, plugins/ipam/dhcp/lease.go, plugins/ipam/dhcp/main.go, plugins/ipam/dhcp/options.go, plugins/ipam/dhcp/options_test.go
Make some DHCP options sent to the server can be set from parsing CNI_ARGS.
This closes #435 and #660.
=> dhcp ipam: support customizing dhcp options from CNI args

plugins/ipam/dhcp/lease.go
DHCP daemon could not get a lease when a retry was needed.  fastRetry caused backoffRetry to exit and not retry.  This change holds off the break from the retry loop until after it is back in normal delay.  This lets a retry happen and leases can be acquired.
=> Fixed DHCP problem that broke when fast retry was added.

plugins/main/bridge/bridge.go, plugins/main/ipvlan/ipvlan.go, plugins/main/loopback/loopback.go, plugins/main/macvlan/macvlan.go, plugins/main/ptp/ptp.go, plugins/main/vlan/vlan.go, plugins/meta/vrf/main.go
=> Ignore NetNS path errors on delete

plugins/main/host-device/host-device.go, plugins/main/host-device/host-device_test.go
If an interface is not configured with IPAM (because it functions at layer 2), it will not be brought up otherwise.
Fixes: #184
=> host-device: Bring interfaces up after moving into container

pkg/ns/ns_linux.go
Use the constants already defined in the golang.org/x/sys/unix package
instead of open-coding them.
=> pkg/ns: use file system magic numbers from golang.org/x/sys/unix

plugins/main/bridge/bridge.go
Related Issue: #680 
Signed-off-by: Michael Zappa <Michael.Zappa@stateless.net>
=> Explicitly Disable Duplicate Address Detection For Container Side Veth

plugins/meta/portmap/portmap.go
checkPorts would return nil rather than an error if the per-container DNAT chain didn't exist, meaning CHECK would erroneously return success rather than failure.
chain.check() already (correctly) checks that the chain exists, so there's no need to do it separately before calling that anyway.
=> portmap: fix checkPorts result when chain does not exist

pkg/utils/conntrack.go
Hello, I found a critical bug that new udp connection deletes all existing conntrack entries.
The `DeleteConntrackEntriesForDstPort` function intended to only delete a conntrack entry that meet the conditions, but calling AddPort before AddProtocol returns an error (`Filter attribute not available without a valid Layer 4 protocol: 0`) and the port filter remains empty.
As a result, ConntrackDeleteFilter deletes all conntrack entries without port filter.
I think this is the simplest PR to resolve this issue, but I'm totally fine if you just ignore this PR and solve this issue in better way.
Just for reference, this bug is affecting our service with latest AKS node image. I recommend someone who are suffering same issue in AKS to build your own plugin binary and inject to worker nodes.
ref: …
=> portmap: fix bug that new udp connection deletes all existing conntrack entries

plugins/meta/tuning/tuning.go, plugins/meta/tuning/tuning_test.go
The tuning-cni allows to set any sysctl on the created container. The admin might however want to restrict the user to a predefined whitelist of sysctls.
This PR is a POC with a proposal on how this could be implemented.
Tuning-cni would try to read a whitelist file from <cni bin dir>/tuningwhitelist/sysctlwhitelist (NOTE: temporary location only), and check the incoming sysctls agains it. Cni would return error if an unathorized sysctl is detected. 
The tuning-cni would behaves as before is the file is missing.
The POC is meant to only show the concept, the actual implementation will probably differ.
=> Add sysctl allowList

plugins/main/bridge/bridge.go
call ipam.ExecDel to release ip in ipam after clean up device in netns.,avoid ip conflict
fix #666
Signed-off-by: gojoy <729324352@qq.com>
=> call ipam.ExecDel after clean up device in netns

README.md
Spent a few days on this not due to misunderstanding the description. I'm hoping this tweak saves someone else working with CNI a lot of headaches in future.
=> Make description for `static` plugin more exact

pkg/hns/endpoint_windows.go, plugins/main/windows/win-overlay/sample-v2.conf, plugins/main/windows/win-overlay/win-overlay_windows.go
This PR bring V2 API support into win-overlay CNI. With the current V1
API, only docker runtime works for win-overlay. By bringing new changes, we
should be able to use containerd as the runtime.Below are the key
points regarding this implementation.
1. Clear seperation for V1 & V2 API support in cmdAdd
2. New cni.conf sample that works for win-overlay
3. cmdDel  handles HCN API changes for V2 API version
Signed-off-by: selansen <esiva@redhat.com>
=> V2 API support for win-overlay CNI

plugins/main/bridge/bridge.go, plugins/main/bridge/bridge_test.go
Previously, the bridge plugin ignored DNS settings returned
from an IPAM plugin (e.g. the host-local plugin parsing
resolv.conf to configure DNS). With this change, the bridge plugin
uses IPAM DNS settings.
Similarly to #388, this change will use incoming DNS settings if set,
otherwise IPAM plugin returned DNS settings
Fixes #431
Signed-off-by: Kern Walster <walster@amazon.com>
=> bridge: support IPAM DNS settings

.github/workflows/test.yaml, scripts/release.sh
Containers are coming to riscv64:
- https://github.com/opencontainers/runc/pull/3463
- https://medium.com/@tonistiigi/early-look-at-docker-containers-on-risc-v-40ed43b16b09
=> build: support riscv64

plugins/meta/portmap/portmap.go
When a problem occurs accessing both iptables and ip6tables in portmap, return an error that contains the origin errors.
Fixes #711
=> bug: return errors when iptables and ip6tables are unusable

plugins/meta/tuning/tuning.go, plugins/meta/tuning/tuning_test.go
The tuning-cni config currently allows to specif duplicated sysctls, also with conflicting values. Duplicated sysctl entries are usually  not used intentionally, but are rather the result of an error in configuration.
This PR adds a check for duplicated sysctl's.
=> Check for duplicated sysctl keys

plugins/ipam/dhcp/lease.go
Currently, hostname is set in the original DHCPREQUEST but not the
renewal. With some DHCP server implementations (such as FreeBSD dhcpd),
this leads to the hostname being cleared in the lease table.
This behavior is inconsistent with other DHCP clients such as dhclient
which set the hostname on the renewal request as well. To fix, use the
same options for acquire and renew.
This is compatible with RFC 2131 (see table 5).
=> Use the same options for acquiring, renewing lease

plugins/ipam/host-local/backend/disk/backend.go, plugins/ipam/host-local/backend/store.go, plugins/ipam/host-local/backend/testing/fake_store.go
This function seems unused and host-local compiles perfectly without it.
=> host-local: remove unused Release(ip) from type Store interface

README.md, plugins/linux_only.txt, plugins/main/dummy/README.md, plugins/main/dummy/dummy.go, plugins/main/dummy/dummy_suite_test.go, plugins/main/dummy/dummy_test.go
Leverages the Linux dummy interface type to create network interfaces
that permit routing packets through the Linux kernel without
them being transmitted.
This solution allows use of arbitrary non-loopback IP addresses within
the container, and leverages existing CNI IPAM plugins.
Related to #466
=> dummy: Create a Dummy CNI plugin that creates a virtual interface.

plugins/meta/portmap/portmap_integ_test.go
GitHub Actions recently updated ubuntu-latest to 22.04 [1], which now
defaults to nfttables (rather than iptables-legacy) [2]. The portmap
tests in this project are written with the expectation that expected
error message for one test is in the iptables-legacy format.
This commit updates the check to make it work for both the
iptables-legecy and iptables-nftables variants.
References:
[1]: https://github.com/actions/runner-images/commit/4aba37bd3b8df82c3b27e7c2448556e966a8b41e
[2]: https://ubuntu.com/blog/whats-new-in-security-for-ubuntu-22-04-lts
Signed-off-by: Emily Shepherd <emily@redcoat.dev>
=> Fix Tests: Update portmap test's iptables error check

pkg/ip/route_linux.go
AddDefaultRoute assumes that the user is adding a default route for IPv4, not IPv6. This pr will fix it.
=> Add IPv6 support for AddDefaultRoute

plugins/meta/portmap/main.go, plugins/meta/portmap/portmap.go
=> `portmap` support masquerade all 

pkg/ip/ipforward_linux.go, pkg/ip/ipforward_linux_test.go, pkg/ns/ns_linux_test.go, pkg/testutils/cmd.go, pkg/testutils/dns.go, pkg/testutils/echo/echo_test.go, pkg/utils/sysctl/sysctl_linux.go, plugins/ipam/dhcp/daemon.go, plugins/ipam/dhcp/dhcp_test.go, plugins/ipam/host-local/backend/disk/backend.go, plugins/ipam/host-local/backend/disk/lock_test.go, plugins/ipam/host-local/dns_test.go, plugins/ipam/host-local/host_local_test.go, plugins/main/bridge/bridge_test.go, plugins/main/dummy/dummy_test.go, plugins/main/host-device/host-device.go, plugins/main/host-device/host-device_test.go, plugins/main/ipvlan/ipvlan_test.go, plugins/main/macvlan/macvlan_test.go, plugins/main/ptp/ptp_test.go, plugins/main/vlan/vlan_test.go, plugins/meta/bandwidth/bandwidth_linux_test.go, plugins/meta/tuning/tuning.go
io/ioutil package has been marked deprecated in Go 1.16.
https://go.dev/doc/go1.16#ioutil
Signed-off-by: Austin Vazquez <macedonv@amazon.com>
=> Remove references to io/ioutil package

plugins/main/bridge/bridge.go
Sometimes the mac address changes after adding the port to the bridge.
Fixes #805
Signed-off-by: Casey Callendrello <c1@caseyc.net>
=> bridge: refresh host-veth mac after port add

plugins/main/vlan/vlan.go, plugins/main/vlan/vlan_test.go
Add support for in-container master for the vlan plugin
docs: https://github.com/containernetworking/cni.dev/pull/109
=> Add support for in-container master for vlans

plugins/main/macvlan/macvlan.go, plugins/main/macvlan/macvlan_test.go
Signed-off-by: mmirecki <mmirecki@redhat.com>
=> Add support for in-container master for macvlans

plugins/main/macvlan/macvlan.go, plugins/main/vlan/vlan.go
this prevents the error to be lost which was causing the panic while accesing a nil var.
Fix #830
Signed-off-by: Marcelo Guerrero Viveros <marguerr@redhat.com>
=> Fix overwritten error var in getMTUByName

test_linux.sh
Removes govet and gofmt from test_linux.sh as they are already addressed by golangci-lint.
Signed-off-by: Matthieu MOREL <matthieu.morel35@gmail.com>
=> remove govet and gofmt from test_linux.sh

.golangci.yml, pkg/testutils/echo/echo_test.go, plugins/main/bridge/bridge_test.go, plugins/meta/bandwidth/ifb_creator.go, plugins/meta/bandwidth/main.go, plugins/meta/firewall/firewall_firewalld_test.go, plugins/meta/tuning/tuning.go, plugins/meta/tuning/tuning_test.go, plugins/meta/vrf/vrf_test.go
Signed-off-by: Matthieu MOREL <matthieu.morel35@gmail.com>
=> enable durationcheck,  predeclared, unconvert, unused and wastedassign linters 

plugins/main/bridge/bridge.go, plugins/main/bridge/bridge_test.go
This new parameter allows users to remove the default vlan
Fixes: #667
=> Add parameter to disable default vlan

plugins/main/bridge/bridge.go, plugins/main/bridge/bridge_test.go
add vlan trunk support for veth
vlan trunk only support L2 only mode without any IPAM
refer ovs-cni design
https://github.com/k8snetworkplumbingwg/ovs-cni/blob/main/pkg/plugin/plugin.go
design:
origin "vlan" option will be PVID or untagged vlan for the network.
"vlanTrunk" will setup tagged vlan for veth.
entry type:
`{ "id": 100 }` will specify only tagged vlan 100
`{ "minID": 100, "maxID": 120 }` will specify tagged vlan from 100 to
120 (include 100 and 120)
vlanTrunk is a list of above entry type, so you can use this to add
tagged vlan
`[
{ "id": 100 },
{
"minID": 1000,
"maxID": 2000
}
]`
complete config will be like this
```json
{
"cniVersion": "0.3.1",
"name": "mynet",
"type": "bridge",
"bridge": "mynet0",
"vlan": 100,
"vlanTrunk": [
{ "id": 101 },
{ "minID": 1000, "maxID": 2000 },
{ …
```
=> bridge: add vlan trunk support

pkg/ip/utils_linux.go, plugins/main/ptp/ptp_test.go
Using ptp plugin with non default routes, we get the following error when cri-o call CheckNetworkList():
```
Expected Route {Dst:{IP:198.18.128.0 Mask:ffff8000} GW:<nil>} not found in routing table
```
Using cniVersion 0.3.1 to bypass the check, we can see that the route is added with a gateway
```
$ ip r
198.18.0.0/17 via 198.18.0.1 dev eth0 src 198.18.3.102
198.18.0.1 dev eth0 scope link src 198.18.3.102
198.18.128.0/17 via 198.18.0.1 dev eth0
```
If GW is nil only check if we have a route with a DST that matches, and ignore the GW.
Fixes #886
=> Fix ValidateExpectedRoute with non default routes and nil GW

plugins/main/tap/tap.go, plugins/main/tap/tap_test.go
This extends the tap plugin API enabling the user to instruct the CNI plugin the created tap device must be set as a port of an *existing* linux bridge on the pod network namespace.
This is helpful for KubeVirt, allowing network connectivity to be extended from the pod's interface into the Virtual Machine running inside the pod.
=> tap: allow for a tap device to be created as a bridge port

plugins/meta/vrf/vrf.go, plugins/meta/vrf/vrf_test.go
Up until now, if previous plugin assigned routes to interface, movement of this interface to new VRF cause routes to be deleted.
This patch adds funtionality to VRF plugin to save the routes before interface is assgined to VRF, and then re-apply all saved routes to new VRF.
Closes: #866
=> Add routes propagation for VRF plugin

.github/workflows/test.yaml
We were getting tip- versions of all the tools, and this was unstable.
=> test: install binaries using `go install`

go.mod, go.sum, pkg/link/spoofcheck.go, pkg/link/spoofcheck_test.go, vendor/github.com/networkplumbing/go-nft/nft/config.go, vendor/github.com/networkplumbing/go-nft/nft/exec/exec.go, vendor/modules.txt
Store the relevant applied config part for later to extract the rule to delete from there instead of having to list the ruleset. This is much faster especially with large rulesets.
=> spoofcheck: Make use of go-nft's ApplyConfigEcho()

plugins/meta/firewall/firewall_firewalld_test.go, test_linux.sh
Patch 1 fixes for unexpected output from dbus-daemon on Fedora Rawhide, patch 2 fixes a spurious error when calling test_linux.sh a second time.
=> Two minor testsuite fixes

pkg/utils/iptables.go, plugins/meta/portmap/chain.go
Patch 1 makes callers use the module-provided ChainExists() method, it is faster than the custom implementation. This does not bump dependencies, the required version of go-iptables in go.mod is already sufficient.
Patch 2 tries to speed up meta/portmap plugin's teardown() by avoiding an expensive ipt.List() call (in big rulesets). Make it fall back to the old code for unexpected cases.
=> Review code using go-iptables module

plugins/ipam/dhcp/dhcp_test.go, test_linux.sh, test_windows.sh
This PR addresses the race conditions discovered during local testing using the Go race command. 
The test named "correctly handles multiple DELs for the same container" in the ipam/dhcp package experiences race conditions when multiple goroutines concurrently access and modify the Args struct (of type CmdArgs). 
Before applying the fix, the race detector logs indicated conflicting accesses as can be seen here:
```
==================
WARNING: DATA RACE
Write at 0x00c00031e630 by goroutine 210:
[github.com/containernetworking/plugins/plugins/ipam/dhcp.rpcCall()](http://github.com/containernetworking/plugins/plugins/ipam/dhcp.rpcCall())
/home/asudakov/go/src/github.com/AlinaSecret/plugins/plugins/ipam/dhcp/main.go:165 +0x35c
[github.com/containernetworking/plugins/plugins/ipam/dhcp.cmdDel()] …
```
=> Fix race conditions in DHCP test

plugins/meta/vrf/vrf.go, plugins/meta/vrf/vrf_test.go
The route filter currently filters based on the `LinkIndex` and `Scope`. The corresponding filter flag for `LinkIndex` should be `netlink.RT_FILTER_OIF`, and not `netlink.RT_FILTER_IIF`. This renders the filter ineffective, causing the wrong routes to be copied into the new VRF.
The [netlink code here](https://github.com/vishvananda/netlink/blob/v1.2.1-beta.2/route_linux.go#L1056-L1059) tells us which filter flags corresponds to which field.
I have a k8s cluster that's using Multus to have multiple interfaces. Here's a concrete example demonstrating this issue:
1. create a pod with 2 interfaces, the default pod CNI and an additional one, say, the bridge CNI
```
lo               UNKNOWN        127.0.0.1/8
eth0@if398       UP             10.244.2.151/24
net1@if399       UP …
```
=> vrf: fix route filter to use output iface

.golangci.yml
This extends the timeout or golangci-lint execution to 5 min as it is only one minute now it fails for several PR.
=> ci(lint) extend timeout to 5 min

build_linux.sh, build_windows.sh, scripts/release.sh, test_linux.sh, test_windows.sh
The scripts didn't really use any bash specific features. Convert them to POSIX shell scripts, so that the plugins can be built without requiring bash.
=> build: Use POSIX sh for shell scripts

.github/dependabot.yml
Rather than endless rebases, just batch all go updates to once a week.
=> dependabot: batch updates

plugins/main/bridge/bridge.go
gws.defaultRouteFound is always false.
firstV4Addr it is declared but not used anywhere in the code.
=> bridge: remove useless code

pkg/testutils/cmd.go
[containernetwork/cni#890](https://github.com/containernetworking/cni/pull/890) introduces CNI_NETNS_OVERRIDE and plugin testing requires this flag. This change enables CNI_NETNS_OVERRIDE for further containernetwork/cni vendor update.
=> Add CNI_NETNS_OVERRIDE for upcoming CNI change

plugins/main/macvlan/macvlan.go
When the master interface on the node has been deleted, and loadConf tries 
to get the MTU, This causes cmdDel to return a linkNotFound error to the
runtime. The cmdDel only needs to unmarshal the net config. No need to
get the MTU. So we just replaced the loadConf function with
json.unmarshal in cmdDel.
Fixes https://github.com/containernetworking/plugins/issues/953
=> macvlan cmdDel: replace the loadConf function with json.unmarshal

plugins/main/bridge/bridge.go, plugins/main/bridge/bridge_test.go
The new `disableContainerInterface` parameter is added to the bridge plugin to
enable setting the container interface state down.
When the parameter is enabled, the container interface (veth peer that is placed
at the container ns) remain down (i.e: disabled).
The bridge and host peer interfaces state are not affected by the parameter.
Notes for reviewers:
- Since IPAM logic involve various configurations including waiting for addresses
to be realized and setting the interface state UP, the new parameter cannot work
with IPAM.
In case both IPAM and DisableContainerInterface parameters are set, the bridge
plugin will raise an error.
- CNI versions 0.1.0 and 0.2.0 result expect single IP addresses, where newer versions expect multiple addresses (slice).
When the new parameter is set, there …
=> bridge: Enable disabling bridge interface

.github/workflows/release.yaml
This change introduces new github action to build cni plugin binaries for each platform at tagged new release.
=> Add github action to build binaries for each platform at release

.github/workflows/test.yaml
currently the workflow will use latest
version which is a moving target.
newer versions may cause ci failures due
to new checks added.
=> Fix version of golangci-lint

.github/workflows/test.yaml, scripts/release.sh
N/A
This change updates the version of Go in CI and release to Go v1.22
- https://go.dev/doc/go1.22
=> Update to Go v1.22 in CI and release

.github/workflows/test.yaml, plugins/main/bridge/bridge.go, plugins/main/dummy/dummy.go, plugins/main/dummy/dummy_test.go, plugins/main/ipvlan/ipvlan.go, plugins/main/macvlan/macvlan.go, plugins/main/tap/tap.go, plugins/main/vlan/vlan.go, plugins/main/vlan/vlan_test.go, plugins/meta/bandwidth/bandwidth_linux_test.go, plugins/meta/sbr/main.go, plugins/meta/vrf/main.go
N/A
This change renames unused parameters in test to resolve linter warnings. It also updates golangci-lint-action package to v4 to resolve NodeJS 16 deprecation warnings.
Lint check passes without deprecation warnings
- https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
=> Update golangci-lint-action package to v4

plugins/main/host-device/host-device.go, plugins/main/host-device/host-device_test.go
Today, it is not possible to use host-device CNI to move a
host device to container namespace if a device with the same
netdev name already exists in that namespace.
e.g when a delegate plugin (such as multus) is used to provide
multiple networks to a container, CNI Add call will fail if
the targeted host device name already exists in container network
namespace.
to overcome this, we use a temporary name for the interface before
moving it in/out of container network namespace.
=> Use temporary name for netdevice when moving in/out of NS

plugins/main/host-device/host-device.go, plugins/main/host-device/host-device_test.go
Device plugins may allocate network device on a bus different than PCI.
sriov-network-device-plugin supports the allocation of network devices over Auxiliary bus[1][2][3].
extend host-device CNI to support such devices if provided through runtime config.
- Check if device provided by DeviceID runtime config is present on either PCI bus or Auxiliary bus
- extend getLink method to support getting netdev link obj from auxiliary bus
- add unit-test to cover the new flow
[1] https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin/tree/master?tab=readme-ov-file#auxiliary-network-devices-selectors
[2] https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin/tree/master/docs/subfunctions
[3] https://docs.kernel.org/networking/devlink/devlink-port.html
=> Support DeviceID on Auxiliary Bus

pkg/ip/link_linux.go, pkg/ip/link_linux_test.go
If makeVeth fails as a peer exists, the existing peer name should be included in the error message.
=> ip: include peer name in error message

.github/workflows/release.yaml
This changes adds BuildVersion linker flag in release to fix CNI plugins output. Fixes #1019.
=> Fix release script in github action

.github/dependabot.yml
We should manage their lifecycle separately.
=> dependabot: don't automatically update cni packages

.github/workflows/release.yaml
Fix #1053
Results with fixed one with this PR
```
$ curl -LO https://github.com/s1061123/plugin-dummy/releases/download/v1.0.0/cni-plugins-linux-amd64-v1.0.0.tgz
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 45.9M  100 45.9M    0     0  9299k      0  0:00:05  0:00:05 --:--:-- 9920k
$ tar tvzfp cni-plugins-linux-amd64-v1.0.0.tgz
drwxr-xr-x runner/docker     0 2024-06-17 10:37 ./
-rwxr-xr-x root/root  11423522 2024-06-17 10:37 ./dhcp
-rwxr-xr-x root/root   3750466 2024-06-17 10:37 ./loopback
-rw-r--r-- root/root      2343 2024-06-17 10:37 ./README.md
-rwxr-xr-x root/root   4272418 2024-06-17 10:37 ./bandwidth
-rwxr-xr-x root/root …
```
=> Fix release tar images' owner to root

.github/workflows/test.yaml
- Fix double-triggering CI
- switch back to hard-coded go version.
=> .github: bump go

plugins/main/macvlan/macvlan.go
This setting was introduced in Linux 5.11
https://github.com/torvalds/linux/commit/d4bff72c8401e6f56194ecf455db70ebc22929e2
https://github.com/iproute2/iproute2/commit/42f5642a40a70e2ad0a10563397d6aa714299390
=> macvlan: add bcqueuelen setting

pkg/ipam/ipam_linux.go, pkg/ipam/ipam_linux_test.go
Add Scope for routes for cni spec v1.1
https://github.com/containernetworking/cni/pull/1068
=> Use of Scope for routes in IPAM

plugins/meta/sbr/sbr_linux_test.go
The tests were flaky due to a route with the link-local IP being automatically added after the test run saves the initial state (routes before SBR plugin is ran). When the SBR plugin is ran, the new state is compared with the old state. The new state will then contain the route with the link-local IP (that has been added after saving the old state), the old state was not containing it, so the tests were failing
The solution here is to ignore routes with the link-local IP for the tests.
fixes: #1096
=> Ignore link-local routes in SBR tests

pkg/ip/link_linux.go, pkg/ipam/ipam_linux_test.go, pkg/ns/README.md, pkg/utils/sysctl/sysctl_linux_test.go, plugins/ipam/dhcp/dhcp_test.go, plugins/main/bridge/bridge.go, plugins/main/bridge/bridge_test.go, plugins/main/dummy/dummy.go, plugins/main/dummy/dummy_test.go, plugins/main/host-device/host-device_test.go, plugins/main/ipvlan/ipvlan.go, plugins/main/ipvlan/ipvlan_test.go, plugins/main/macvlan/macvlan.go, plugins/main/macvlan/macvlan_test.go, plugins/main/tap/tap.go, plugins/main/tap/tap_test.go, plugins/main/vlan/vlan.go, plugins/main/vlan/vlan_test.go, plugins/meta/bandwidth/bandwidth_suite_test.go, plugins/meta/firewall/firewall_iptables_test.go, plugins/meta/sbr/sbr_linux_test.go, plugins/meta/tuning/tuning_test.go, plugins/meta/vrf/vrf.go, plugins/meta/vrf/vrf_test.go
When diagnosing networking issues, I noticed that `txqueuelen` on `veth` pairs and `tap` devices was set to zero. In investigating the issue, I found that most usages of `netlink.LinkAttrs` in this repository uses the struct literal, which in the `netlink` docs is advised against unless `TxQLen` is explicitly set.
> Note `NewLinkAttrs` constructor, it sets default values in structure. For now it sets only `TxQLen` to `-1`, so kernel will set default by itself. If you're using simple initialization(`LinkAttrs{Name: "foo"}`) `TxQLen` will be set to `0` unless you specify it like `LinkAttrs{Name: "foo", TxQLen: 1000}`.
> ([link](https://pkg.go.dev/github.com/vishvananda/netlink#section-readme))
When using the `ip` command directly without specifying `txqueuelen`, Linux will automatically to …
=> Fix inadvertent txqueuelen being set to zero

pkg/ns/ns_linux.go, plugins/main/host-device/host-device.go
Using a temporary name / doing a fast rename causes some race conditions with udev and NetworkManager: https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/issues/1599
Fixes #1072
=> host-device: use temp network namespace for rename

plugins/meta/vrf/vrf.go, plugins/meta/vrf/vrf_test.go
Without waiting for the local/host routes to be added by the kernel after the IP address is being added to an interface. The routes requiring the local/host routes may failed. This caused flaky e2e tests, but could also happen during the execution of the VRF plugin when the IPv6 addresses were being re-added to the interface and when the route were being moved to the VRF table.
fixes: #1103
=> VRF: Wait for the local/host routes to be added

pkg/ipam/ipam.go, pkg/ipam/ipam_linux.go, pkg/testutils/cmd.go, pkg/testutils/testing.go, plugins/main/bridge/bridge.go, plugins/main/bridge/bridge_test.go, plugins/main/dummy/dummy.go, plugins/main/dummy/dummy_test.go, plugins/main/host-device/host-device.go, plugins/main/host-device/host-device_test.go, plugins/main/ipvlan/ipvlan.go, plugins/main/ipvlan/ipvlan_test.go, plugins/main/macvlan/macvlan.go, plugins/main/macvlan/macvlan_test.go, plugins/main/ptp/ptp.go, plugins/main/ptp/ptp_test.go, plugins/main/tap/tap.go, plugins/main/tap/tap_test.go, plugins/main/vlan/vlan.go, plugins/main/vlan/vlan_test.go, plugins/main/windows/win-bridge/win-bridge_windows.go, plugins/main/windows/win-overlay/win-overlay_windows.go, plugins/sample/main.go
This PR fixes the missing parts of #1050 (pass STATUS to a delegated plugin)
I also updated the cni dependency to v1.2.3
=> Pass status along ipam update

plugins/meta/portmap/portmap_nftables.go, plugins/meta/portmap/portmap_nftables_test.go
We can't use dnat from the input hook,
depending on nftables (and kernel ?) version we get
"Error: Could not process rule: Operation not supported"
iptables backend also uses prerouting.
Also 'ip6 protocol tcp' is invalid, so rework / simplify the rules
Fixes 01a94e17c77e6ff8e5019e15c42d8d92cf87194f
Fixes #1115
=> portmap: fix nftables backend

plugins/meta/portmap/main.go, plugins/meta/portmap/portmap_test.go
As show in the docs, iptables conditions can also start with '!'
Fixes 01a94e17c77e6ff8e5019e15c42d8d92cf87194f
Fixes #1114
=> portmap: fix iptables conditions detection

plugins/main/host-device/host-device.go, plugins/main/host-device/host-device_test.go
It would be nice to see the interface name in network-status pod annotation when called by multus, or other meta plugin when the host device is bound to a userspace driver.
For e.g. when I have a NAD as follows, and attach it to a pod
```
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
annotations:
k8s.v1.cni.cncf.io/resourceName: openshift.io/pci_sriov_vf
name: net-a
spec:
config: |-
{
"cniVersion": "1.0.0",
"name": "net-a",
"type": "host-device",
"pciBusID": "0000:07:00.0",
"ipam": {}
}
```
k8s.v1.cni.cncf.io/network-status: |-
[{
"name": "ovn-kubernetes",
"interface": "eth0",
"ips": [
"fd02:0:0:1::2ed"
],
"mac": "0a:58:70:d0:c0:27",
"default": true,
"dns": {}
},{
"name": "sriramy/net-a",
"interface": "net1",
"dns": {},
"device-info": {
"type": "pci", …
=> host-device: Return interface name in result

plugins/meta/firewall/firewall.go, plugins/meta/firewall/firewall_integ_test.go, plugins/meta/firewall/ingresspolicy.go
IngressPolicyIsolated ("isolated") behaves  similar to ingress policy "same-bridge" with the exception that connections from the same bridge are also blocked. This is meant to be functionally equivalent to Docker network option "enable_icc" when set to false.
Resolves: #1107
=> Add a new firewall ingress-policy "isolated"

plugins/meta/vrf/vrf.go, plugins/meta/vrf/vrf_test.go
Fix addresses and routes reinserted to the VRF
These changes make sure that only IPV6 global addresses and non local/connected routes are reinserted to the VRF table after slaving the interface
Issue:
Consistent failure
```
plugin type="vrf" failed (add): cmdAdd failed: failed getting local/host addresses for net1 in table 1 with dst fe80::2204:fff:fef1:88a1/64
```
After slaving an interface to a VRF, global IPV6 addresses (unless a sysctl option is enabled) are lost. The plugin gets the IPV6 addresses after and before slaving the interface and adds the ones that are missing. It checks that those addresses are present in the kernel to prevent failures when adding missing global routes associated with these addresses (subsequent operation). There is a retrying mechanism for checking the …
=> Fix addresses and routes reinserted to the VRF

plugins/meta/vrf/vrf.go
The current max waiting time for global IPV6 addresses to be present in the kernel after reinserting them is not sufficient for all use cases. SRIOV + VRF takes around 1.2s.
These changes increase the maximum waiting time to approximately 2.5s. An exponential backoff is implemented to reduce cpu overload.
=> Implement exponential backoff in vrf plugin

pkg/ip/addr_linux.go, pkg/ipam/ipam_linux.go
IPv6 configuration is valid if DAD does not fail
=> Check error returned by ipv6 SettleAddresses

.github/workflows/test.yaml, plugins/meta/firewall/firewall_integ_test.go
- create a throwaway test root netns
- modprobe `br-netfilter` so iptables rules are executed for intra-bridge traffic.
Fixes: #1182
=> Firewall: fix CI

plugins/main/bridge/bridge.go, plugins/main/bridge/bridge_test.go
This allows to set the native vlan on trunk ports
via the vlan parameter. It removes all previous
limitations set on the vlan trunk implementation.
=> Allow vlan parameter to set native vlan on trunk ports

plugins/main/bridge/bridge.go
Default behavior of the vlan implementation on the bridge should guarantee complete vlan isolation. This complies with what regular users expect from the vlan feature.
=> Set default value of PreserveDefaultVlan to False

.github/workflows/test.yaml
Need a newer version to upgade the action.
=> .github: bump golangci-lint version

plugins/ipam/dhcp/lease.go
Default behavior of the plugin is to try and install routes without using SRC which prevents routes from being installed in the routing table in (some) cloud environment that assign /32 IPs to NICs. This change enables routes to be installed without this value (and making the scope to be set to SCOPE_LINK. Another way of fixing it would be if the plugin would be refactored to use the SRC object of the struct in github.com/vishvananda/netlink which would require more work and potentially impact other plugins.
=> Set value of gw to nil for opt121 routes in DHCP

plugins/main/dummy/dummy.go, plugins/main/dummy/dummy_test.go
When the root net ns has "eth0", dummy CNI returns errror "failed to create dummy: file exists"
The fix is to create the dummy interface directly in the pod net ns
=> Fix file exists errro in dummy cni
