.travis.yml
build

I mostly cargo-culted this from the cni repo.

travis integration

---

.gitignore
CONTRIBUTING.md
Vagrantfile

Copied from CNI repo with small tweaks.

Add CONTRIBUTING and Vagrantfile

---

Godeps/Godeps.json
vendor/github.com/coreos/go-iptables/iptables/iptables.go

vendor: bump go-iptables to 0.2.0

---

Godeps/Godeps.json
pkg/ipam/ipam.go
pkg/ipam/ipam_test.go
plugins/ipam/host-local/host_local_test.go
plugins/main/bridge/bridge.go
plugins/main/ipvlan/ipvlan.go
plugins/main/macvlan/macvlan.go
plugins/main/ptp/ptp.go
plugins/main/vlan/vlan.go
plugins/meta/portmap/main.go
plugins/meta/portmap/portmap_integ_test.go
plugins/meta/portmap/portmap_test.go
plugins/sample/main.go
vendor/github.com/containernetworking/cni/pkg/invoke/args.go
vendor/github.com/containernetworking/cni/pkg/invoke/raw_exec.go
vendor/github.com/containernetworking/cni/pkg/types/020/types.go
vendor/github.com/containernetworking/cni/pkg/types/current/types.go
vendor/github.com/containernetworking/cni/pkg/types/types.go

It's a pointer now, so we need to use the helper function to set the field and also test for nil before accessing it.

pkg,plugins: update for Result struct Interface index changes

---

RELEASING.md
scripts/release.sh

Copied from containernetworking/cni
The only difference is that the release archives also include the the
word "plugin"

Add release process

---

build.sh

This will let people build ELF binaries on OS X (addresses #27)

If we're on OS X then have Go cross compile for us

---

pkg/testutils/echosvr/echosvr_test.go
pkg/testutils/echosvr/init_test.go
pkg/testutils/echosvr/main.go
plugins/meta/portmap/portmap_suite_test.go

A little follow-up to https://github.com/containernetworking/plugins/pull/71#issuecomment-327509129

testing: move echosvr into testutils

---

plugins/main/host-device/README.md
plugins/main/host-device/host-device.go
plugins/main/host-device/host-device_test.go

This plugin needed some cleaning up: it didn't generate output, and didn't test DEL. Add those things, plus a README.

plugins/main/host-device: generate result, fix DEL, other cleanups

---

README.md

See also: https://github.com/containernetworking/cni/pull/516

README: add Windows CI badge

---

plugins/main/ipvlan/README.md

Keep the doc consistent with code.

Update IPVLAN modes by adding l3s in README.

---

plugins/main/host-device/host-device.go
plugins/main/host-device/host-device_test.go

On ADD save the host device's name into its IFLA_ALIAS property and
rename the device to the requested CNI_IFNAME inside the container
to conform to the CNI specification.  On DEL rename the device to
the original name and move it back into the host namespace.

host-device: respect CNI_IFNAME/args.IfName

---

plugins/main/macvlan/macvlan.go

We encounter link and ip leak in production, one reason on cni side is that it not recycle resource when err happens. 
We first meet the issue in macvlan plugin, however this issue appears in other plugins as well, if this modification is reasonable I will apply the change to other plugins.

delete link and ip if err when cmdAdd to avoid resource leak.

---

Godeps/Godeps.json
pkg/ip/link_linux.go
pkg/ip/link_linux_test.go
vendor/github.com/safchain/ethtool/ethtool.go

Just cherry-picking commits from #75 so that we can use them in #96 also.
cc @dcbw @squeed

Adds GetVethPeerIfindex library function

---

Godeps/Godeps.json
pkg/ip/ipmasq_linux.go
vendor/github.com/coreos/go-iptables/NOTICE
vendor/github.com/coreos/go-iptables/iptables/iptables.go

Fixes containernetworking/cni#539

pkg/ip: Tearing down ipmasq should be idempotent

---

pkg/ip/link_linux.go
plugins/main/bridge/bridge_test.go
plugins/main/ptp/ptp_test.go

pkg/ip: re-fetch the created link to return creation-time parameters

---

plugins/ipam/static/main.go

remove duplicated assginment.
Signed-off-by: CuiHaozhi <61755280@qq.com>

remove duplicated assginment.

---

Godeps/Godeps.json
vendor/github.com/coreos/go-iptables/NOTICE
vendor/github.com/coreos/go-iptables/iptables/iptables.go

Pick up iptables-nftables support.
NOTE: This is a merge in to the v0.7 branch to fix an existing bug. I'll forward-port this to master after this merges.

vendor: bump coreos/go-iptables

---

plugins/meta/portmap/chain.go

portmap: don't panic if listing a chain returns fewer lines than exected

---

Godeps/Godeps.json
vendor/github.com/coreos/go-iptables/NOTICE
vendor/github.com/coreos/go-iptables/iptables/iptables.go

This reverts commit ffb78af3aff69b87f645ac19e9556bdd1c2475e7.
@dcbw

Revert "vendor: bump coreos/go-iptables"

---

README.md

Also standardized to upper case for sentence starts.
Cheers,
Angela

Updated README to include bandwidth plugin

---

Godeps/Godeps.json
plugins/ipam/dhcp/daemon.go
plugins/ipam/dhcp/dhcp_test.go
plugins/ipam/dhcp/main.go
test.sh
vendor/github.com/d2g/dhcp4server/leasepool/lease_test.go
vendor/github.com/d2g/dhcp4server/leasepool/memorypool/memorypool.go
vendor/github.com/d2g/dhcp4server/leasepool/memorypool/memorypool_test.go
vendor/github.com/d2g/dhcp4server/server.go
vendor/github.com/d2g/dhcp4server/server_test.go

vendor: update dhcp4server 
Bring plugins/vendor/github.com/d2g/dhcp4server up to date.
Fixes #206

Fix vendor regression in dhcp4server

---

DCO

DCO referenced from CONTRIBUTING.md did not exist. Add it (copied from CNI repository).

Add missing DCO

---

pkg/ipam/ipam.go
plugins/meta/bandwidth/bandwidth_linux_test.go
plugins/meta/flannel/flannel.go
plugins/meta/flannel/flannel_linux.go
plugins/meta/flannel/flannel_windows.go
plugins/meta/portmap/portmap_integ_test.go
vendor/github.com/containernetworking/cni/libcni/api.go
vendor/github.com/containernetworking/cni/libcni/conf.go
vendor/github.com/containernetworking/cni/pkg/invoke/delegate.go
vendor/github.com/containernetworking/cni/pkg/invoke/exec.go
vendor/github.com/containernetworking/cni/pkg/invoke/raw_exec.go
vendor/github.com/containernetworking/cni/pkg/skel/skel.go
vendor/github.com/containernetworking/cni/pkg/types/current/types.go
vendor/github.com/containernetworking/cni/pkg/types/types.go
vendor/github.com/containernetworking/cni/pkg/version/version.go

Vendor github.com/containernetworking/cni libcni and pkg file needed for CHECK
Update plugins/tests to deal with changes made to this vendor'ed code
Fixes #226

Vendor github.com/containernetworking/cni libcni and pkg

---

CONTRIBUTING.md

I hit some minor issues when I tried to run the tests using vagrant. I've updated the instructions to reflect what I found.

Tweak contributing instructions to clarify how to run tests.

---

plugins/ipam/host-local/backend/allocator/range.go
plugins/ipam/host-local/backend/allocator/range_test.go

remove gateway check 

---

plugins/ipam/dhcp/README.md
plugins/ipam/dhcp/daemon.go
plugins/ipam/dhcp/main.go

Fix -hostprefix option

---

Godeps/Godeps.json
vendor/github.com/containernetworking/cni/pkg/invoke/raw_exec.go

Really just for cleanliness purposes.

vendor: bump cni to v0.7.0

---

plugins/main/windows/win-bridge/win-bridge_windows.go
plugins/main/windows/win-overlay/win-overlay_windows.go
plugins/meta/flannel/flannel.go

windows,flannel: cmdGet -> cmdCheck and fix flannel Check return

---

pkg/ipam/ipam.go
plugins/main/bridge/bridge.go
plugins/main/host-device/host-device.go
plugins/main/ipvlan/ipvlan.go
plugins/main/macvlan/macvlan.go
plugins/main/ptp/ptp.go
plugins/main/vlan/vlan.go

Have ipam.ExecDel set CNI_COMMAND to DEL

---

.travis.yml
Godeps/Godeps.json
vendor/github.com/safchain/ethtool/.gitignore
vendor/github.com/safchain/ethtool/Makefile
vendor/github.com/safchain/ethtool/README.md
vendor/github.com/safchain/ethtool/ethtool.go
vendor/github.com/safchain/ethtool/ethtool_cmd.go

Update github.com/safchain/ethtool to fix the compilation
error on 386. Also added 386 to the tarvis yaml.
Fixes #322
Signed-off-by: Moshe Levi <moshele@mellanox.com>

fix compilation error on 386

---

Vagrantfile

update go to the latest version v1.12.7

update Go version in Vagrantfile

---

plugins/ipam/static/README.md
plugins/ipam/static/main.go
plugins/ipam/static/static_test.go
plugins/meta/tuning/README.md
plugins/meta/tuning/tuning.go
plugins/meta/tuning/tuning_test.go

Support "args" field in JSON config to additional configuration in static and tuning plugin.

Support "args" in static and tuning

---

.travis.yml

See: https://golang.org/doc/go1.13

Bump Go version

---

OWNERS.md

As agreed on the recent maintainers call.
Welcome @mars1024 and @jellonek to the team!

Add Bruce Ma and Piotr Skarmuk as owners

---

plugins/meta/firewall/README.md

Document `CNI-ADMIN` chain usage as well as `iptablesAdminChainName`
closes #504

Update firewall README.md

---

plugins/ipam/host-local/main.go

Remove unused function

---

plugins/meta/bandwidth/bandwidth_linux_test.go

Check error before using return value.

bandwidth: fix panic in tests

---

plugins/ipam/dhcp/client.go
plugins/ipam/dhcp/daemon.go
plugins/ipam/dhcp/lease.go
plugins/ipam/dhcp/main.go

Setting this new flag resolves #440 for me
```
dchp daemon -broadcast=true
```

ipam/dhcp: Add broadcast flag

---

plugins/ipam/dhcp/README.md
plugins/ipam/host-local/README.md
plugins/ipam/static/README.md
plugins/main/bridge/README.md
plugins/main/host-device/README.md
plugins/main/ipvlan/README.md
plugins/main/macvlan/README.md
plugins/main/ptp/README.md
plugins/main/windows/win-bridge/README.md
plugins/main/windows/win-overlay/README.md
plugins/meta/bandwidth/README.md
plugins/meta/firewall/README.md
plugins/meta/flannel/README.md
plugins/meta/portmap/README.md
plugins/meta/sbr/README.md
plugins/meta/tuning/README.md
plugins/meta/vrf/README.md

Fix broken links to online docs in plugin READMEs

---

go.mod
go.sum
vendor/github.com/containernetworking/cni/libcni/api.go
vendor/github.com/containernetworking/cni/pkg/invoke/find.go
vendor/github.com/containernetworking/cni/pkg/types/040/types.go
vendor/github.com/containernetworking/cni/pkg/types/internal/convert.go
vendor/modules.txt

Nothing exciting, but it looks nice.

vendor: bump to libcni v1.0-rc1

---

README.md

Small typo improves
Signed-off-by: André Franciosi <andre@franciosi.org>

Small typo improves in README.md

---

plugins/main/bridge/bridge.go

Signed-off-by: Takuya Noguchi <takninnovationresearch@gmail.com>

bridge: Fix typo in error message for promiscuous mode

---

go.mod
go.sum
plugins/main/windows/win-bridge/win-bridge_windows.go
plugins/main/windows/win-overlay/win-overlay_windows.go
plugins/meta/bandwidth/main.go
plugins/meta/firewall/firewall.go
plugins/meta/vrf/main.go
vendor/github.com/containernetworking/cni/pkg/version/version.go
vendor/modules.txt

 plugins: fix bug where support for CNI version 0.4.0 or 1.0.0 was dropped

---

plugins/main/host-device/host-device.go
plugins/main/host-device/host-device_test.go

fixes #578 
Signed-off-by: Periyasamy Palanisamy <periyasamy.palanisamy@est.tech>

host-device: add ipam support for dpdk device

---

plugins/ipam/dhcp/lease.go
plugins/main/bridge/bridge.go

This picks two fixes:
- #702 
- #709

[release-1.1] Cherry-pick some bugfixes

---

.github/workflows/stale.yml

Signed-off-by: Casey Callendrello <cdc@redhat.com>

workflow: add something to auto-close stale PRs

---

.github/workflows/test.yaml
scripts/release.sh

Signed-off-by: Casey Callendrello <cdc@redhat.com>

Bump to go 1.18

---

OWNERS.md

Signed-off-by: Michael Zappa <michael.zappa@gmail.com>

Update email to gmail

---

plugins/ipam/dhcp/daemon.go
plugins/ipam/dhcp/lease.go

Previously, the Allocate method of the daemon always created a new Lease object. However, as both the CNI ADD and CHECK commands call Allocate, and CHECK can be called multiple times, this resulted in multiple Lease objects being created per pod.
Each of these leases was long lived with its own maintain() loop - however the daemon only kept track of the most recent one, meaning any old lease objects remained running forever (and held open their NetNS files). After a long enough period, this resulted in the system crashing out with "too many files" or a similar error limits-related error.
This commit updates the behaviour of Allocate() to first check if a Lease already exists for the given clientID. If none is found, one is created as before. If a Lease is found, a new Check() mechanism is …

Update Allocate method to reuse lease if present

---

go.mod
go.sum
vendor/github.com/safchain/ethtool/ethtool.go
vendor/modules.txt

Signed-off-by: Matthieu MOREL <matthieu.morel35@gmail.com>

build(deps): bump github.com/safchain/ethtool to v0.2.0

---

plugins/meta/portmap/portmap.go

Only check or del ipv6 when an IPv6 is configured
Fixes #819 
Signed-off-by: Michael Cambria <mccv1r0@gmail.com>

Only check or del ipv6 when an IPv6 is configured

---

.golangci.yml
pkg/ns/ns_linux_test.go

Fix a small ginkgo compare issue, and ignore dot imports.

fix lint errors

---

.github/workflows/test.yaml

This is executing checkout first and using go.mod's go version to setup go.
Signed-off-by: Matthieu MOREL <matthieu.morel35@gmail.com>

fix workflow warnings

---

plugins/main/bridge/bridge.go

revert !gws.defaultRouteFound remove in pr #962

revert some code in pr 962

---

.github/workflows/release.yaml

Fix #1053 (user wants to change tar ball directory permission as well)

Change chown to change current dir as well

---

.github/workflows/test.yaml

Make sure we don't slip any changes in there accidentally.

.github: add check to verify vendor directory

---

test_linux.sh

These are disabled by default in some distros; we would like to test rootless, however.

test: enable unpriv user namespaces
